import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

function readSource(relativePath) {
  return readFileSync(new URL(relativePath, import.meta.url), 'utf8');
}

test('EAGLE GREEN separates Galileo large-event routing from the VIP confidentiality guardrail', () => {
  const demoSource = readSource('../../demo/ciscoLiveDemo.ts');
  const seedSource = readSource('../../demo/ciscoLiveSeed.ts');
  const configureSource = readSource('../../pages/agent/ActionConfigureV2.tsx');
  const controlsSource = readSource('../../pages/agent/ActionControls.tsx');
  const sessionsSource = readSource('../../pages/agent/AgentSessions.tsx');
  const policyStudioSource = readSource('../../pages/agent/SecurityUIPolicyStudio.tsx');
  const overviewSource = readSource('../../pages/agent/AgentStudioLanding.tsx');
  const studioStyles = readSource('../../products/ai-agent-studio/components.css');

  assert.match(
    demoSource,
    /CISCO_LIVE_VIP_EVENT_CONFIDENTIALITY_GUARDRAIL[\s\S]*?id:\s*['"]custom-vip-event-confidentiality['"][\s\S]*?name:\s*['"]VIP event confidentiality['"][\s\S]*?action:\s*['"]block['"][\s\S]*?direction:\s*['"]both['"]/,
  );
  assert.match(
    demoSource,
    /CISCO_LIVE_PRIMARY_GUARDRAILS\s*=\s*\[[\s\S]*?CISCO_LIVE_VIP_EVENT_CONFIDENTIALITY_GUARDRAIL[\s\S]*?\]/,
    'the confidentiality policy should be part of the primary agent seed',
  );
  assert.match(
    demoSource,
    /id:\s*CISCO_LIVE_PRIMARY_AGENT_ID[\s\S]*?customGuardrails:\s*CISCO_LIVE_PRIMARY_GUARDRAILS/,
    'EAGLE GREEN should receive the seeded custom guardrails',
  );
  assert.match(
    configureSource,
    /ciscoLiveAgent\.customGuardrails\.map\(guardrail => \(\{[\s\S]*?enabled:\s*true/,
    'seeded custom guardrails should start enabled',
  );
  assert.match(
    seedSource,
    /markConfigured\(draft\.familyConfiguration,\s*['"]security['"],\s*getCiscoLiveGuardrailNames\(definition\),\s*now\)/,
    'the seeded policy should configure the Overview Security capability',
  );
  assert.match(
    seedSource,
    /EAGLE_GREEN_ACTION_CONTROL_VALUES[\s\S]*?name:\s*['"]Route large event requests to the VIP team['"][\s\S]*?timing:\s*['"]post_tool['"][\s\S]*?behavior:\s*['"]steer['"][\s\S]*?field:\s*['"]party_size['"][\s\S]*?value:\s*100[\s\S]*?field:\s*['"]requested_bays['"][\s\S]*?value:\s*20[\s\S]*?prerequisiteControlIds/,
    'the large-event threshold should be stored as an action control and gate, not a guardrail',
  );
  assert.match(controlsSource, /label:\s*`\$\{activeCount\} active\$\{behavior \? ` · \$\{behavior\}` : ''\}`/);
  assert.match(controlsSource, /Gated · 1 prerequisite/);
  assert.match(controlsSource, /Make this action available only after prerequisites match/);
  assert.match(
    configureSource,
    /customGuardrails:\s*advancedCustomItems[\s\S]*?initialDirection=\{editItem\?\.direction\}[\s\S]*?direction:\s*result\.direction/,
    'custom guardrail definitions and Direction should survive save and refresh',
  );
  assert.match(configureSource, /Custom guardrails/);
  assert.match(configureSource, /Create guardrail/);
  assert.match(policyStudioSource, /DEFAULT_CUSTOM_GUARDRAIL_NAME\s*=\s*['"]VIP event confidentiality['"]/);
  assert.doesNotMatch(policyStudioSource, /medical advice|healthcare clinic|Large reservation approval/);
  assert.match(
    demoSource,
    /id:\s*['"]SES-GT-1042['"][\s\S]*?guardrailTriggered:\s*false[\s\S]*?actionControlTriggered:\s*LARGE_EVENT_ACTION_CONTROL\.event\.actionControl\.matched[\s\S]*?id:\s*['"]SES-GT-1045['"][\s\S]*?guardrailTriggered:\s*true/,
    'the large-event and confidentiality stories should remain separate sessions',
  );
  assert.match(sessionsSource, /event\.kind === ['"]action_control['"][\s\S]*?Action control/);
  assert.match(
    studioStyles,
    /\.agent-session-metadata-icons\s*>\s*\.agent-session-metadata-icons__action-control\s*\{[\s\S]*?color:\s*var\(--mds-color-theme-common-text-primary-normal,\s*#fff\)/,
    'the Action control session badge should use a white foreground for both its label and inherited icon',
  );
  assert.match(
    demoSource,
    /createSeededActionControlEvent[\s\S]*?evaluateGalileoActionInvocation[\s\S]*?LARGE_EVENT_ACTION_CONTROL/,
    'seeded session decisions should be generated by the deterministic evaluator',
  );
  assert.match(
    sessionsSource,
    /getSessionActionControlDecision[\s\S]*?session\.transcript\.flatMap[\s\S]*?event\.actionControl/,
    'Session detail should derive its decision from the transcript event',
  );
  assert.doesNotMatch(sessionsSource, /session\.actionControl(?:\?|\.|!)/);
  assert.doesNotMatch(demoSource, /CISCO_LIVE_LARGE_RESERVATION_GUARDRAIL|custom-large-reservation-approval/);
  assert.match(
    overviewSource,
    /const configuredSecurity = configuredCapabilityLabels\(agentDraft,\s*['"]security['"]\)[\s\S]*?chips:\s*configuredSecurity\.map\(item => \(\{\s*item,\s*type:\s*['"]guardrail['"]/,
    'the Connected card should render configured Security policies as guardrail chips',
  );
});

test('EAGLE GREEN upgrades legacy state and normalizes action names', () => {
  const contextSource = readSource('../../contexts/AppContext.tsx');
  const policyStudioSource = readSource('../../pages/agent/SecurityUIPolicyStudio.tsx');

  assert.match(contextSource, /schemaVersion:\s*7/);
  assert.match(
    contextSource,
    /shouldMigrateLegacyActions\s*=\s*storedSchemaVersion\s*<\s*4[\s\S]*?hasStoredSelections[\s\S]*?hasCheckAvailabilityControls[\s\S]*?!Array\.isArray\(checkAvailabilityControls\)/,
    'schema-3 drafts should receive missing Galileo defaults while explicit empty control arrays remain intact',
  );
  assert.match(
    contextSource,
    /shouldMigrateCheckAvailabilityName\s*=\s*storedSchemaVersion\s*<\s*6[\s\S]*?item === ['"]Check Availability\.['"][\s\S]*?return ['"]Check Availability['"]/,
    'schema-5 drafts should normalize the Check Availability display name without changing its stable action ID',
  );
  assert.match(
    contextSource,
    /shouldMigrateLargeEventControlTiming\s*=\s*storedSchemaVersion\s*<\s*7[\s\S]*?control\.id === EAGLE_GREEN_ACTION_CONTROL_ID[\s\S]*?nextControl\.timing = seededLargeEventControl\.timing/,
    'schema-6 drafts should migrate only the canonical large-event control to post-action timing',
  );
  assert.match(
    contextSource,
    /LEGACY_LARGE_RESERVATION_GUARDRAIL_ID\s*=\s*['"]custom-large-reservation-approval['"][\s\S]*?LEGACY_LARGE_RESERVATION_GUARDRAIL_NAME\s*=\s*['"]large reservation approval['"]/,
  );
  assert.match(
    contextSource,
    /migrateStoredCustomGuardrails\(securityValues\.customGuardrails\)[\s\S]*?customGuardrails:\s*customGuardrailsMigration\.value/,
    'stored custom guardrail objects should migrate during AppContext hydration',
  );
  assert.match(
    contextSource,
    /if \(!isLegacyLargeReservationGuardrail\(item\)\) return \[item\][\s\S]*?structuredClone\(CISCO_LIVE_VIP_EVENT_CONFIDENTIALITY_GUARDRAIL\)[\s\S]*?versions:\s*\[\]/,
    'unrelated user guardrails should remain while the legacy object receives the complete current definition',
  );
  assert.match(policyStudioSource, /All rules shown below/);
  assert.doesNotMatch(policyStudioSource, /items\.slice|overview\.edgeCases\.slice/);
});

test('operational status shows a compact session event table filtered by the selected time range', () => {
  const source = readSource('../../pages/agent/AgentStudioLanding.tsx');

  assert.match(
    source,
    /const operationalSessions = getCiscoLiveSessions\(agent\.id(?:,\s*actionConfigurationValues)?\)[\s\S]*?\.filter\(session => sessionAgeHours\(session\.updated\) <= operationalTimeRangeHours\)[\s\S]*?\.slice\(0,\s*3\)/,
    'sessions should respect the selected time range and stay compact',
  );
  assert.match(
    source,
    /className="agent-studio-operational-overview"[\s\S]*?<\/div>[\s\S]*?<section[\s\S]*?className="agent-studio-session-events"[\s\S]*?<Table className="agent-studio-session-events__table"/,
    'the session table should remain directly below the operational metrics',
  );
  assert.match(
    source,
    /<section[\s\S]*?className="agent-studio-session-events"[\s\S]*?className="agent-studio-session-events__actions"[\s\S]*?Open Sessions[\s\S]*?<Table className="agent-studio-session-events__table"/,
    'Open Sessions should sit in the session events header',
  );
  assert.match(
    source,
    /<TableHeader>Channel<\/TableHeader>[\s\S]*?<TableHeader>Session ID<\/TableHeader>[\s\S]*?<TableHeader>Customer<\/TableHeader>[\s\S]*?<TableHeader>Messages<\/TableHeader>[\s\S]*?<TableHeader>Updated<\/TableHeader>[\s\S]*?<TableHeader>Outcome<\/TableHeader>[\s\S]*?<TableHeader>Event<\/TableHeader>/,
  );
  assert.match(
    source,
    /if \(outcome === ['"]Transferred['"]\) return ['"]warning['"][\s\S]*?if \(outcome === ['"]Resolved['"]\) return ['"]success['"]/,
    'transferred sessions should use the yellow warning treatment while resolved sessions remain green',
  );
});

test('Agent Studio header saves configuration changes before publishing a new version', () => {
  const source = readSource('../../pages/agent/AgentStudioLanding.tsx');
  const handlerStart = source.indexOf('const handlePublishVersion');
  const headerActionsStart = source.indexOf('const headerActions =');
  const headerActionsEnd = source.indexOf('const sessionsDeepLink', headerActionsStart);
  const handlerSource = source.slice(handlerStart, headerActionsStart);
  const headerActionsSource = source.slice(headerActionsStart, headerActionsEnd);

  assert.ok(handlerStart >= 0 && headerActionsStart > handlerStart && headerActionsEnd > headerActionsStart);
  assert.match(handlerSource, /publishAgentVersion\(agent\.id\)/);
  assert.match(handlerSource, /Published version \$\{publishedDraft\.version\}/);
  assert.match(handlerSource, /const hasUnsavedConfigurationChanges[\s\S]*?currentAgentRevision !== overviewReleaseState\.savedRevision/);
  assert.match(handlerSource, /const releaseActionLabel = hasSavedConfigurationReadyToPublish \? ['"]Publish['"] : ['"]Save['"]/);
  assert.match(handlerSource, /const handleReleaseAction[\s\S]*?showToast\(['"]Configuration saved['"], ['"]success['"]\)[\s\S]*?handlePublishVersion\(\)/);
  assert.match(
    headerActionsSource,
    /disabled=\{releaseActionDisabled\}[\s\S]*?onClick=\{handleReleaseAction\}[\s\S]*?\{releaseActionLabel\}/,
    'the action should be disabled without changes, then progress from Save to Publish',
  );
  assert.doesNotMatch(headerActionsSource, /Duplicate as…/);
});

test('overview cards can be reordered and persist their layout per agent', () => {
  const source = readSource('../../pages/agent/AgentStudioLanding.tsx');
  const styles = readSource('../../products/ai-agent-studio/components.css');

  assert.match(
    source,
    /const DEFAULT_OVERVIEW_CARD_ORDER:\s*OverviewCardId\[\]\s*=\s*\[[\s\S]*?['"]capability['"][\s\S]*?['"]operational['"][\s\S]*?\]/,
  );
  assert.match(source, /readOverviewTileOrder\(agentId,\s*['"]cards['"],\s*DEFAULT_OVERVIEW_CARD_ORDER\)/);
  assert.match(source, /persistOverviewTileOrder\(agent\.id,\s*group,\s*nextOrder\)/);
  assert.match(
    source,
    /overviewCardOrder\.map\(\(cardId,\s*index\)[\s\S]*?handleOverviewTileDragStart\(event,\s*['"]cards['"],\s*cardId\)[\s\S]*?handleOverviewTileKeyDown\(event,\s*['"]cards['"],\s*cardId\)/,
    'the main cards should share the drag and keyboard reordering model',
  );
  assert.match(
    styles,
    /\.agent-studio-overview-card__drag-handle\s*\{[^}]*top:\s*var\(--spacing-x-small\);[^}]*right:\s*var\(--spacing-x-small\);[^}]*width:\s*28px;/,
    'large overview card handles should align with the smaller tile handles in the upper-right corner',
  );
});

test('capability summary cards navigate to their respective configuration sections', () => {
  const source = readSource('../../pages/agent/AgentStudioLanding.tsx');
  const styles = readSource('../../products/ai-agent-studio/components.css');

  const sectionMapPattern =
    /OVERVIEW_SUMMARY_CONFIGURATION_SECTION[\s\S]*?knowledge:\s*['"]Knowledge['"][\s\S]*?memory:\s*['"]Knowledge['"][\s\S]*?actions:\s*['"]Action['"][\s\S]*?guardrails:\s*['"]Security['"]/;
  assert.match(
    source,
    sectionMapPattern,
    'summary cards should map to the matching configuration destinations',
  );
  assert.match(
    source,
    /className="agent-studio-connected-summary__link"[\s\S]*?configure\?section=\$\{OVERVIEW_SUMMARY_CONFIGURATION_SECTION\[item\.id\]\}[\s\S]*?aria-label=\{`Open \$\{item\.label\} configuration`\}/,
    'each summary card should expose a native, named configuration link',
  );
  assert.match(
    source,
    /className="agent-studio-overview-tile__drag-handle"[\s\S]*?draggable[\s\S]*?handleOverviewTileDragStart\(event,\s*['"]summary['"],\s*item\.id\)/,
    'reordering should remain isolated to the drag handle',
  );
  assert.match(styles, /\.agent-studio-connected-summary__link\s*\{[^}]*height:\s*100%;/);
  assert.match(
    styles,
    /\.agent-studio-connected-summary__link:hover\s*\{[^}]*background:[^}]*text-decoration:\s*none;/,
    'the hover surface should fill the card without inheriting the global link underline',
  );
  assert.match(styles, /\.agent-studio-connected-summary__link:focus-visible\s*\{[^}]*outline:/);
});

test('Voice channel progressively reveals and persists its three routing fields', () => {
  const configureSource = readSource('../../pages/agent/ActionConfigureV2.tsx');
  const dropdownSource = readSource('../../components/shared/Dropdown.tsx');
  const modelSource = readSource('./agentCreationModel.ts');
  const styles = readSource('../../components.css');

  assert.match(
    configureSource,
    /selectedChannels\.includes\(['"]voice['"]\)[\s\S]*?<fieldset className="v2-voice-channel-fields">[\s\S]*?label="Location"[\s\S]*?label="Phone number"[\s\S]*?label="Extension"/,
    'Voice should reveal exactly the location, phone number, and extension fields',
  );
  assert.match(
    configureSource,
    /VOICE_LOCATION_OPTIONS[\s\S]*?🇺🇸 San Francisco headquarters[\s\S]*?🇺🇸 New York customer support[\s\S]*?🇬🇧 London reservations desk/,
    'each location should pair a visible country flag with a specific geographic label',
  );
  assert.match(
    configureSource,
    /const updateVoiceChannelField[\s\S]*?values:\s*\{[\s\S]*?\.\.\.\(channelsCap\?\.values \?\? \{\}\),[\s\S]*?\[field\]: value/,
    'voice edits should merge into the existing channel values instead of replacing channel selection',
  );
  assert.match(
    configureSource,
    /configurationFingerprint[\s\S]*?channelConfigurationValues[\s\S]*?\[[\s\S]*?channelConfigurationValues/,
    'all voice fields should participate in the Save fingerprint',
  );
  assert.match(
    configureSource,
    /label="Extension"[\s\S]*?inputMode="numeric"[\s\S]*?pattern="\[0-9\]\*"[\s\S]*?maxLength=\{8\}[\s\S]*?replace\(\/\\D\/g, ['"]['"]\)/,
    'the extension should preserve leading zeroes while accepting no more than eight digits',
  );
  assert.match(
    modelSource,
    /interface ContactCenterChannelValues[\s\S]*?voiceLocation\?: string;[\s\S]*?voicePhoneNumber\?: string;[\s\S]*?voiceExtension\?: string;/,
  );
  assert.match(
    styles,
    /\.v2-voice-channel-fields__grid\s*\{[^}]*grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\);[\s\S]*?@media \(max-width:\s*900px\)[\s\S]*?grid-template-columns:\s*1fr;/,
    'the three fields should align in one desktop row and stack on narrow screens',
  );
  assert.match(
    dropdownSource,
    /htmlFor=\{triggerId\}[\s\S]*?aria-labelledby=\{label \? `\$\{labelId\} \$\{valueId\}` : valueId\}[\s\S]*?aria-describedby=\{hint \? hintId : undefined\}/,
    'Dropdown labels, selected values, and hints should be announced together',
  );
});

test('Galileo table controls use the shared Momentum button component', () => {
  const configureSource = readSource('../../pages/agent/ActionConfigureV2.tsx');
  const styles = readSource('../../components.css');

  assert.match(
    configureSource,
    /<td className="col-galileo">[\s\S]*?<Button[\s\S]*?variant="secondary"[\s\S]*?color=\{galileoButtonColor\}[\s\S]*?size="sm"[\s\S]*?className=\{`galileo-action-control-button is-\$\{galileoStatus\.tone\}`\}/,
    'table status actions should use the shared Momentum button and its semantic color API',
  );
  assert.match(
    styles,
    /\.galileo-action-control-button\.btn\s*\{[^}]*justify-content:\s*flex-start;[^}]*max-width:\s*100%;/,
    'table-specific styling should only constrain the Momentum button layout',
  );
  assert.doesNotMatch(
    styles,
    /\.galileo-action-control-status\s*\{/,
    'the table should not keep a parallel custom button implementation',
  );
});

test('Actions exposes the Galileo recommendation flow beside Add actions', () => {
  const configureSource = readSource('../../pages/agent/ActionConfigureV2.tsx');
  const controlsSource = readSource('../../pages/agent/ActionControls.tsx');
  const styles = readSource('../../components.css');

  assert.match(
    configureSource,
    /className="action-config-v2-action-actions"[\s\S]*?<Button[\s\S]*?variant="secondary"[\s\S]*?className="action-config-v2-recommended-btn"[\s\S]*?aria-haspopup="dialog"[\s\S]*?<Icon name="sparkle"[\s\S]*?Recommend Controls[\s\S]*?className="add-action-menu-wrapper"/,
    'Recommend Controls should be the first page action and use the sparkle icon beside Add actions',
  );
  assert.match(
    configureSource,
    /const openRecommendedControls = \(\) => \{[\s\S]*?setShowAddMenu\(false\);[\s\S]*?setShowRecommendedControls\(true\);[\s\S]*?onClick=\{openRecommendedControls\}/,
    'opening recommendations should close the Add actions menu before showing the dialog',
  );
  assert.match(
    controlsSource,
    /title="Recommended action controls"[\s\S]*?Nothing is published automatically\./,
    'the dialog should explain that generated controls are not published automatically',
  );
  assert.match(
    controlsSource,
    /Preparing agent context[\s\S]*?Analyzing requirements[\s\S]*?Validating safe controls/,
    'the dialog should preserve the staged Galileo analysis flow from the demo',
  );
  assert.match(
    controlsSource,
    /Saved instruction evidence[\s\S]*?Why this control[\s\S]*?Happy path[\s\S]*?Intervention path[\s\S]*?Manual review gaps/,
    'recommendations should explain their evidence and known evaluator gaps',
  );
  assert.match(
    controlsSource,
    /status: 'needs_review'[\s\S]*?source: 'recommended'/,
    'adding a recommendation should require review instead of publishing it automatically',
  );
  assert.match(
    styles,
    /\.action-config-v2-action-actions\s*\{[^}]*flex-wrap:\s*wrap;[\s\S]*?\.recommended-controls-dialog\s*\{[^}]*width:\s*min\(1120px/,
    'the paired actions and recommendation dialog should remain responsive',
  );
  assert.match(
    styles,
    /\.action-config-v2-recommended-btn svg\s*\{[^}]*color:\s*currentColor;/,
    'the sparkle icon should match the white button label instead of using the accent color',
  );
});

test('Galileo intervention behavior uses a native radio group', () => {
  const controlsSource = readSource('../../pages/agent/ActionControls.tsx');
  const styles = readSource('../../components.css');

  assert.match(
    controlsSource,
    /<RadioGroup[\s\S]*?name=\{`galileo-action-control-behavior-\$\{contextActionId\}`\}[\s\S]*?label="Control behavior"[\s\S]*?value=\{draft\.behavior\}[\s\S]*?<Radio key=\{behavior\} value=\{behavior\} label=\{BEHAVIOR_LABELS\[behavior\]\} \/>/,
    'Observe, Steer, and Deny should use the shared native RadioGroup pattern',
  );
  assert.doesNotMatch(
    controlsSource,
    /aria-label="Intervention behavior"[\s\S]*?aria-pressed=\{draft\.behavior === behavior\}/,
    'the behavior selector should not retain segmented-button semantics',
  );
  assert.match(
    styles,
    /\.galileo-action-control-behavior \.radio-group-list\s*\{[^}]*flex-direction:\s*row;[^}]*flex-wrap:\s*wrap;/,
    'the compact behavior radio group should stay horizontal and wrap safely',
  );
});

test('Galileo keeps the control summary and editor in one full-page modal', () => {
  const controlsSource = readSource('../../pages/agent/ActionControls.tsx');
  const styles = readSource('../../components.css');

  assert.match(
    controlsSource,
    /<main className="galileo-action-control-workspace">[\s\S]*?className="galileo-action-control-summary"[\s\S]*?className="galileo-action-control-editor"/,
    'the outcome summary and editable fields should share one continuous modal workspace',
  );
  assert.doesNotMatch(
    controlsSource,
    /className="security-ui-workspace galileo-action-control-studio__workspace"|className="galileo-action-control-dialog__body"/,
    'the continuous workspace should not be wrapped in an additional layout container',
  );
  assert.doesNotMatch(
    controlsSource,
    /useState<['"]summary['"] \| ['"]editor['"]>|Back to summary|Edit control<\/Button>/,
    'view and edit should not be split into separate modal modes',
  );
  assert.match(
    controlsSource,
    /Control summary[\s\S]*?summaryCopy\.lead[\s\S]*?<dt>Evaluation<\/dt>[\s\S]*?<dt>If<\/dt>[\s\S]*?<dt>Then<\/dt>[\s\S]*?<dt>Otherwise<\/dt>/,
    'the summary should explain the evaluation point and both matched and unmatched outcomes',
  );
  assert.doesNotMatch(
    controlsSource,
    /<summary>Why Galileo recommended this control<\/summary>/,
    'the full-page editor should not repeat recommendation provenance',
  );
  assert.match(
    controlsSource,
    /previousDocumentOverflow[\s\S]*?document\.documentElement\.style\.overflow = ['"]hidden['"][\s\S]*?document\.body\.style\.overflow = ['"]hidden['"][\s\S]*?document\.documentElement\.style\.overflow = previousDocumentOverflow[\s\S]*?document\.body\.style\.overflow = previousBodyOverflow/,
    'the full-page editor should lock and restore document scrolling',
  );
  assert.match(controlsSource, /<span>Action control<\/span>/);
  assert.match(
    controlsSource,
    /<h2 id="galileo-action-control-title" className="security-ui-studio-name">\s*\{contextActionName\}\s*<\/h2>/,
    'the workspace title should use only the action name',
  );
  assert.doesNotMatch(controlsSource, /Galileo · \{contextActionName\}/);
  assert.doesNotMatch(controlsSource, /className="security-ui-version"/);
  assert.match(
    controlsSource,
    /className="security-ui-overlay security-ui-overlay--studio galileo-action-control-studio-overlay"[\s\S]*?className="security-ui-studio galileo-action-control-studio"[\s\S]*?className="security-ui-studio-header galileo-action-control-studio__header"[\s\S]*?<main className="galileo-action-control-workspace">/,
    'the unified workspace should reuse the Policy Studio full-page container pattern',
  );
  assert.match(
    styles,
    /\.galileo-action-control-workspace\s*\{[^}]*display:\s*flex;[^}]*flex:\s*1;[^}]*width:\s*100%;[^}]*min-height:\s*0;[^}]*overflow:\s*auto;[^}]*overscroll-behavior:\s*contain;/,
    'the unwrapped action-control workspace should own scrolling directly',
  );
  const workspaceRule = styles.match(/\.galileo-action-control-workspace\s*\{([^}]*)\}/)?.[1] ?? '';
  assert.doesNotMatch(workspaceRule, /padding:/, 'the unwrapped workspace should not add four-sided padding');
  assert.match(
    styles,
    /\.galileo-action-control-workspace::\-webkit-scrollbar-thumb\s*\{[^}]*background:\s*transparent;[\s\S]*?\.galileo-action-control-workspace:hover::\-webkit-scrollbar-thumb\s*\{[^}]*scrollbar-background-secondary-normal/,
    'the parent workspace should use the shared ghost scrollbar pattern',
  );
});

test('the Actions table owns Galileo control status without a duplicate page banner', () => {
  const source = readSource('../../pages/agent/ActionConfigureV2.tsx');

  assert.doesNotMatch(
    source,
    /Galileo recommendation is active|Galileo found 1 recommended control|galileo-action-control-recommendation/,
    'the Actions page should not repeat row-level Galileo status in a page banner',
  );
  assert.match(
    source,
    /className="col-galileo">Galileo<[\s\S]*?className="galileo-action-control-button/,
    'Galileo status and its control entry point should remain available in each action row',
  );
});

test('action control activity discloses the latest matching decision from the matched path', () => {
  const source = readSource('../../pages/agent/AgentStudioLanding.tsx');
  const styles = readSource('../../products/ai-agent-studio/components.css');

  assert.match(
    source,
    /<figure[\s\S]*?className="agent-studio-action-control-flow"[\s\S]*?aria-labelledby="agent-studio-action-control-flow-caption"[\s\S]*?<figcaption[\s\S]*?\{actionControlFlowLabel\}/,
    'the aggregate should retain a screen-reader summary without hiding its interactive branch',
  );
  assert.match(
    source,
    /Control checks[\s\S]*?Evaluated[\s\S]*?Matched[\s\S]*?Gated action unlocked/,
    'the flow should show its evaluated total and the matched decision path',
  );
  assert.match(
    source,
    /actionControlMatchedOutcomes\.map\(outcome => \{[\s\S]*?outcome\.id === ['"]steered['"][\s\S]*?className="agent-studio-action-control-flow__outcome-primary"[\s\S]*?\{outcome\.label\}[\s\S]*?className="agent-studio-action-control-flow__outcome-connector"[\s\S]*?className="agent-studio-action-control-flow__outcome-detail"[\s\S]*?Gated action unlocked/,
    'a gated-action unlock should appear below Steered with a vertical connector',
  );
  assert.match(
    styles,
    /\.agent-studio-action-control-flow__outcome-connector\s*\{[^}]*width:\s*1px;[^}]*height:\s*14px;[^}]*background:[^}]*\}[\s\S]*?\.agent-studio-action-control-flow__outcome-connector::after\s*\{[^}]*border-right:[^}]*border-bottom:[^}]*rotate\(45deg\);/,
    'the vertical connector should keep the directional cue between the two outcome labels',
  );
  assert.doesNotMatch(
    source,
    /className="agent-studio-action-control-flow__outcome-primary">[\s\S]{0,160}<strong>\{outcome\.value\}<\/strong>/,
    'the matched outcome should not repeat a separate count',
  );
  assert.doesNotMatch(
    source,
    /<small>\{(?:actionControlFlow\.matchRate|actionControlNoMatchRate)\}%<\/small>|<span>Original action ran<\/span>/,
    'the compact decision flow should not repeat percentages or render an unmatched outcome card',
  );
  assert.doesNotMatch(
    source,
    /agent-studio-action-control-flow__label">\s*<i|agent-studio-action-control-flow__outcome::before/,
    'the compact flow labels should not render decorative bullet points',
  );
  assert.match(
    source,
    /agent-studio-action-control-flow__metric[\s\S]*?actionControlFlow\.matched[\s\S]*?agent-studio-action-control-flow__label[\s\S]*?Matched/,
    'the matched decision card should present its large count before its supporting label',
  );
  assert.match(
    source,
    /const actionControlSpotlightDecision = \[\.\.\.actionControlDecisions\][\s\S]*?\.filter\(decision => decision\.matched\)[\s\S]*?\.sort\(/,
    'the spotlight should independently resolve the latest matched decision',
  );
  assert.match(
    source,
    /className=\{`agent-studio-action-control-flow__row agent-studio-action-control-flow__matched-trigger[\s\S]*?aria-expanded=\{showSelectedActionControlDecision\}[\s\S]*?aria-controls="agent-studio-action-control-decision-banner"[\s\S]*?setSelectedOverviewIntervention\(current =>/,
    'the complete matched path should be a native disclosure button linked to the concrete decision banner',
  );
  assert.match(
    source,
    /\(showSelectedGuardrailDecision \|\| showSelectedActionControlDecision\)[\s\S]*?id=\{showSelectedActionControlDecision[\s\S]*?'agent-studio-action-control-decision-banner'[\s\S]*?title=\{showSelectedGuardrailDecision[\s\S]*?['"]VIP event details protected['"][\s\S]*?actionControlSpotlightUnlocked[\s\S]*?['"]Large event transfer unlocked['"][\s\S]*?['"]Standard path redirected['"]/,
    'the latest matching decision should render only while its matched path is expanded',
  );
  assert.doesNotMatch(
    source,
    /Latest matching decision|Selected guardrail decision/,
    'expanded decision banners should begin with the concrete event instead of a redundant generic title',
  );
  assert.match(
    styles,
    /\.agent-studio-action-control-flow__rows\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\);[^}]*align-items:\s*start;[^}]*justify-items:\s*center;/,
    'the matched path should occupy a single centered column',
  );
  assert.match(
    styles,
    /\.agent-studio-action-control-flow__matched-trigger\s*\{[^}]*display:\s*grid;[^}]*width:\s*50%;[^}]*min-width:\s*116px;/,
    'the centered matched path should retain a compact card width',
  );
  assert.match(
    styles,
    /\.agent-studio-action-control-flow__matched-trigger\s*\{[^}]*display:\s*grid;[^}]*grid-template-columns:\s*minmax\(0, 1fr\);[^}]*grid-template-rows:\s*auto 20px auto;/,
    'the matched path should stack its decision and outcome cards vertically',
  );
  assert.doesNotMatch(
    source,
    /agent-studio-action-control-flow__(?:row-divider|row is-unmatched)|No match/,
    'the compact flow should not render the removed unmatched column or its previous divider',
  );
  assert.doesNotMatch(
    source,
    /agent-studio-action-control-flow__column-headings|<span>Decision<\/span>|<span>Outcome<\/span>/,
    'the compact flow should not repeat Decision and Outcome headings above the cards',
  );
  assert.match(
    styles,
    /\.agent-studio-action-control-flow__summary\s*\{[^}]*border:\s*var\(--border-width-small\) solid var\(--border-color\);[^}]*background:\s*color-mix\(in srgb, var\(--bg-primary\) 74%, transparent\);/,
    'the evaluated summary should use the neutral Uplift card surface instead of an accent border',
  );
  assert.doesNotMatch(
    styles,
    /\.agent-studio-action-control-flow__summary-icon\s*\{[^}]*(?:background|border-radius):/,
    'the control-check icon should render directly without a background tile',
  );
  assert.match(
    styles,
    /\.agent-studio-action-control-flow__line\s*\{[^}]*width:\s*1px;[^}]*height:\s*20px;[^}]*justify-self:\s*center;[^}]*background:\s*color-mix\(in srgb, var\(--text-secondary\) 58%, transparent\);/,
    'the matched decision should connect vertically to its outcome with a neutral line',
  );
  assert.match(
    styles,
    /\.agent-studio-action-control-flow__outcome\.is-unlocked\s*\{[^}]*align-items:\s*center;[^}]*text-align:\s*center;[^}]*\}[\s\S]*?\.agent-studio-action-control-flow__outcome\.is-unlocked\s+\.agent-studio-action-control-flow__outcome-primary\s*\{[^}]*justify-content:\s*center;[^}]*\}[\s\S]*?\.agent-studio-action-control-flow__outcome\.is-unlocked\s+\.agent-studio-action-control-flow__outcome-connector\s*\{[^}]*margin-left:\s*0;/,
    'the steered outcome content and its internal connector should be centered',
  );
  assert.doesNotMatch(
    styles,
    /\.agent-studio-action-control-flow__row\.is-matched \.agent-studio-action-control-flow__(?:line(?:::after)?|decision|outcome:first-child)\s*\{|\.agent-studio-action-control-flow__outcome\.is-unlocked\s*\{[^}]*(?:border-color|background):/,
    'the matched path should not add an arrowhead, blue connector, accent border, or accent card background',
  );
  assert.match(
    styles,
    /\.agent-studio-action-control-flow__matched-trigger:hover:not\(:disabled\)\s*\{[^}]*background:\s*color-mix\(in srgb, var\(--bg-secondary\) 42%, transparent\);[^}]*box-shadow:\s*0 0 0 var\(--border-width-small\) var\(--border-color\);[^}]*\}[\s\S]*?\.agent-studio-action-control-flow__matched-trigger\.is-selected\s*\{[^}]*background:\s*color-mix\(in srgb, var\(--bg-secondary\) 58%, transparent\);[^}]*box-shadow:[^}]*var\(--border-color\),[^}]*var\(--elevation-1\);/,
    'the disclosure should use neutral Uplift surfaces for hover and expanded states instead of an accent border',
  );
  assert.match(
    styles,
    /\.agent-studio-action-control-flow__matched-trigger\.is-selected\s+\.agent-studio-action-control-flow__decision,\s*\.agent-studio-action-control-flow__matched-trigger\.is-selected\s+\.agent-studio-action-control-flow__outcome\s*\{[^}]*background:\s*color-mix\(in srgb, var\(--bg-secondary\) 58%, var\(--bg-primary\)\);/,
    'the expanded matched decision and outcome cards should receive a darker neutral fill',
  );
  assert.match(
    styles,
    /\.agent-studio-action-control-flow__decision\s*\{[^}]*border:\s*var\(--border-width-small\) solid color-mix\(in srgb, var\(--border-color\) 74%, transparent\);[\s\S]*?\.agent-studio-action-control-flow__outcome\s*\{[^}]*border:\s*var\(--border-width-small\) solid color-mix\(in srgb, var\(--border-color\) 74%, transparent\);/,
    'both matched-path cards should retain the same neutral outline as the surrounding cards',
  );
  assert.match(
    styles,
    /\.agent-studio-action-control-flow__decision\s*\{[^}]*flex-direction:\s*column;[^}]*align-items:\s*flex-start;[^}]*justify-content:\s*center;[^}]*gap:\s*var\(--spacing-micro\);[\s\S]*?\.agent-studio-action-control-flow__label\s*\{[^}]*color:\s*var\(--text-secondary\);[^}]*font-weight:\s*var\(--font-weight-regular\);[\s\S]*?\.agent-studio-action-control-flow__metric\s*\{[^}]*align-items:\s*flex-start;/,
    'decision cards should use the summary-card hierarchy: count above a muted left-aligned label',
  );
  assert.doesNotMatch(
    source,
    /selectedActionControlMetric|ActionControlActivityMetricId|aria-pressed=\{isSelected\}/,
    'aggregate action-control counts should not pretend to be mutually exclusive filters',
  );
});

test('overview and navigation reuse the same capability icon language', () => {
  const categoryIconSource = readSource('../../components/shared/ConfigurationCategoryIcon.tsx');
  const sidebarSource = readSource('../../products/ai-agent-studio/components/Sidebar.tsx');
  const overviewSource = readSource('../../pages/agent/AgentStudioLanding.tsx');

  assert.match(
    categoryIconSource,
    /type === ['"]action['"][\s\S]*?<Icon name="tools" weight="regular"/,
    'Actions should use the Tools icon with the same visual weight as the other overview glyphs',
  );
  assert.match(
    sidebarSource,
    /section:\s*['"]Knowledge['"][\s\S]*?icon:\s*<KnowledgeBookIcon size=\{24\} \/>/,
    'Knowledge navigation should reuse the overview book icon',
  );
  assert.match(
    overviewSource,
    /Maintain healthy coverage[\s\S]*?<KnowledgeBookIcon size=\{16\} \/>|<KnowledgeBookIcon size=\{16\} \/>[\s\S]*?Maintain healthy coverage/,
    'the knowledge coverage suggestion should use the same book icon',
  );
});

test('agent navigation uses the floating Uplift rail with collapse and expand handles', () => {
  const sidebarSource = readSource('../../products/ai-agent-studio/components/Sidebar.tsx');
  const layoutSource = readSource('../../components/layout/MainLayout.tsx');
  const styles = readSource('../../products/ai-agent-studio/components.css');

  assert.match(
    sidebarSource,
    /className="sidebar uplift-agent-panel"[\s\S]*?aria-label="Collapse agent navigation"[\s\S]*?className="sidebar-agent-back-link"[\s\S]*?<Icon name="list-menu" weight="bold" size=\{20\}[\s\S]*?<h2>Progress<\/h2>/,
    'the expanded agent rail should preserve the Uplift hierarchy and collapse control',
  );
  assert.match(
    sidebarSource,
    /className="uplift-agent-panel-handle"[\s\S]*?aria-label="Open agent navigation"[\s\S]*?openAgentPanel\(true\)/,
    'the collapsed rail should leave a discoverable expand handle',
  );
  assert.match(
    sidebarSource,
    /icon="dashboard-bold"[\s\S]*?label="Overview"[\s\S]*?active=\{isOverviewRoute\}/,
    'Overview should use the same icon and selected state as the Uplift rail',
  );
  assert.doesNotMatch(
    sidebarSource,
    /sidebar-agent-pill__name|sidebar-agent-pill__meta/,
    'the agent identity belongs in the page header instead of competing with navigation',
  );
  assert.match(
    styles,
    /\.uplift-agent-panel\s*\{[^}]*position:\s*absolute\s*!important;[^}]*width:\s*232px\s*!important;[^}]*border-radius:\s*12px\s*!important;/,
    'the rail should use the Uplift floating glass-card contract',
  );
  assert.match(
    styles,
    /\.uplift-agent-panel-handle\s*\{[^}]*width:\s*20px;[^}]*height:\s*40px;/,
    'the collapsed handle should retain the Uplift dimensions',
  );
  assert.match(
    layoutSource,
    /agentPanelOpen[\s\S]*?app--ai--agent-panel-open[\s\S]*?agentPanelOpen=\{agentPanelOpen\}[\s\S]*?onAgentPanelOpenChange=\{setAgentPanelOpen\}/,
    'the application shell should own and expose the floating rail state',
  );
});

test('configuration and monitor destinations reuse the Overview page-heading contract', () => {
  const headingSource = readSource('../../components/agents/AgentWorkspacePageHeading.tsx');
  const configureSource = readSource('../../pages/agent/ActionConfigureV2.tsx');
  const testingSource = readSource('../../pages/agent/AgentAnalytics.tsx');
  const sessionsSource = readSource('../../pages/agent/AgentSessions.tsx');
  const historySource = readSource('../../pages/agent/AgentHistory.tsx');
  const productStyles = readSource('../../products/ai-agent-studio/components.css');
  const sharedStyles = readSource('../../components.css');

  assert.match(
    headingSource,
    /className="agent-workspace-page-heading"[\s\S]*?<h1 id=\{id\}>\{title\}<\/h1>[\s\S]*?agent-workspace-page-heading__actions/,
    'each destination should render one reusable page-level heading and action row',
  );
  assert.match(
    configureSource,
    /CONFIGURATION_PAGE_TITLES[\s\S]*?Knowledge:\s*['"]Knowledge & Memory['"][\s\S]*?Action:\s*['"]Actions['"][\s\S]*?className="primary-content action-config-v2-page agent-workspace-page"[\s\S]*?<AgentWorkspacePageHeading title=\{pageTitle\} actions=\{pageActions\}/,
    'all configuration destinations should use the shared title contract',
  );
  assert.match(testingSource, /className="primary-content agent-workspace-page"[\s\S]*?<AgentWorkspacePageHeading title="Testing"/);
  assert.match(sessionsSource, /className="primary-content agent-workspace-page"[\s\S]*?<AgentWorkspacePageHeading[\s\S]*?title="Sessions"/);
  assert.match(historySource, /className="primary-content agent-workspace-page"[\s\S]*?<AgentWorkspacePageHeading title="History"/);
  assert.match(
    productStyles,
    /\.agent-studio-landing,\s*\.agent-workspace-page\s*\{[^}]*gap:\s*var\(--spacing-medium\);/,
    'Overview and the other agent pages should share the same vertical rhythm',
  );
  assert.match(
    productStyles,
    /\.agent-studio-hero h1,\s*\.agent-workspace-page-heading h1\s*\{[^}]*font-size:\s*var\(--font-size-heading-midsize\);[^}]*font-weight:\s*var\(--font-weight-bold\);[^}]*line-height:\s*var\(--font-lineheight-heading-midsize\);[^}]*letter-spacing:\s*-0\.01em;/,
    'all destination titles should inherit the exact Overview typography declaration',
  );
  assert.match(
    sharedStyles,
    /\.action-config-v2-page\s*\{[^}]*padding-top:\s*var\(--spacing-large\);/,
    'configuration pages should use the same 24px top offset as Overview',
  );
  assert.match(
    sharedStyles,
    /\.action-config-v2-page\s*>\s*\.agent-workspace-page-heading\s*\{[^}]*position:\s*relative;[^}]*z-index:\s*3;/,
    'configuration page menus should stack above the table content',
  );
  assert.match(
    sharedStyles,
    /\.action-config-v2-table\s*\{[^}]*min-width:\s*1232px;[\s\S]*?\.action-config-v2-table \.col-action-name\s*\{\s*width:\s*168px;[\s\S]*?\.action-config-v2-table \.col-created-by\s*\{\s*width:\s*112px;[\s\S]*?\.action-config-v2-table \.col-description\s*\{\s*width:\s*350px;/,
    'the Actions table should keep identity columns compact and reserve enough width for readable descriptions',
  );
  assert.match(
    configureSource,
    /action-config-v2-table-wrap action-config-v2-table-wrap--actions[\s\S]*?action-config-v2-table action-config-v2-table--actions/,
    'the Actions table should use its responsive, no-horizontal-scroll layout',
  );
  assert.match(
    sharedStyles,
    /\.action-config-v2-table-wrap--actions\s*\{[^}]*overflow-x:\s*hidden;[\s\S]*?\.action-config-v2-table--actions\s*\{[^}]*min-width:\s*0;[\s\S]*?\.action-config-v2-table--actions \.col-action-name\s*\{\s*width:\s*16%;[\s\S]*?\.action-config-v2-table--actions \.col-created-by\s*\{\s*width:\s*8%;[\s\S]*?\.action-config-v2-table--actions \.col-description\s*\{\s*width:\s*19%;[\s\S]*?\.action-config-v2-table--actions \.col-galileo\s*\{\s*width:\s*18%;/,
    'the responsive Actions table should fit the Galileo status and row actions without horizontal scrolling',
  );
  assert.match(
    sharedStyles,
    /\.add-action-menu\s*\{[^}]*isolation:\s*isolate;[^}]*overflow:\s*hidden;[^}]*border:\s*var\(--border-width-small\) solid var\(--border-color\);[^}]*background:\s*rgba\(0,\s*0,\s*0,\s*0\.84\);[^}]*backdrop-filter:\s*blur\(40px\) saturate\(115%\);[^}]*-webkit-backdrop-filter:\s*blur\(40px\) saturate\(115%\);/,
    'the Add actions menu should retain a complete dark-glass border and strong backdrop blur',
  );
  assert.doesNotMatch(configureSource, /<h3 className="(?:v2-channels__title|action-config-v2-title)">(?:Channels|Profile|Actions)<\/h3>/);
});

test('overview suggestions stay hidden while the section is paused', () => {
  const overviewSource = readSource('../../pages/agent/AgentStudioLanding.tsx');
  assert.match(
    overviewSource,
    /const SHOW_CONNECTED_SUGGESTIONS = false;[\s\S]*?\{SHOW_CONNECTED_SUGGESTIONS && \([\s\S]*?className="agent-studio-connected-insights"/,
    'the Suggestions section should remain out of the rendered overview',
  );
});

test('operational status presents its metrics as a compact table with a dashboard link', () => {
  const studioSource = readSource('../../pages/agent/AgentStudioLanding.tsx');
  assert.match(
    studioSource,
    /const observabilityPath = `\/observability\?agent=\$\{encodeURIComponent\(agent\.name\)\}`;/,
    'the dashboard action should preserve the current agent filter',
  );
  assert.match(
    studioSource,
    /className="agent-studio-operational-metrics-table"[\s\S]*?<th scope="col">Metric<\/th>[\s\S]*?<th scope="col">Value<\/th>[\s\S]*?<th scope="col">Change<\/th>[\s\S]*?OPERATIONAL_HEALTH_METRICS\.map/,
    'the operational metrics should remain compact and scannable',
  );
  assert.match(
    studioSource,
    /onClick=\{\(\) => navigate\(observabilityPath\)\}[\s\S]*?View observability dashboard/,
    'the detailed dashboard should remain one explicit action away',
  );
  assert.doesNotMatch(studioSource, /<KPICard|<KPIChart/);
});

test('selected guardrail banner opens a concrete session detail', () => {
  const studioSource = readSource('../../pages/agent/AgentStudioLanding.tsx');
  const sessionsSource = readSource('../../pages/agent/AgentSessions.tsx');

  assert.match(
    studioSource,
    /selectedGuardrail && selectedGuardrail\.count > 0[\s\S]*?<Banner[\s\S]*?className="agent-studio-operational-event-banner agent-studio-connected-event-banner"[\s\S]*?label: 'View session →'[\s\S]*?navigate\(operationalSessionPath\)/,
    'the selected guardrail event should appear below the capability charts and link to its session',
  );
  assert.match(studioSource, /aria-pressed=\{selectedGuardrailName === guardrail\.item\}/);
  assert.match(
    studioSource,
    /const nextGuardrail = selectedGuardrailName === guardrail\.item[\s\S]*?\? null[\s\S]*?: guardrail\.item;[\s\S]*?setSelectedGuardrailActivity\(nextGuardrail\)/,
    'clicking the selected guardrail should clear the selection and hide its event banner',
  );
  assert.match(
    studioSource,
    /actionControlSpotlightDecision\.sessionId[\s\S]*?SES-GT-1045/,
    'the action-control spotlight should use its derived Session while the guardrail keeps its separate Session',
  );
  assert.match(studioSource, /source=observability/);
  assert.match(sessionsSource, /const activeSession = sessionIdQuery[\s\S]*?sessions\.find/);
  assert.match(sessionsSource, />Session details</);
  assert.match(sessionsSource, /Conversation transcript/);
  assert.match(
    sessionsSource,
    /Back to observability[\s\S]*?\/observability\?agent=\$\{encodeURIComponent\(agent\.name\)\}/,
    'sessions opened from Observability should return to the filtered dashboard',
  );
  assert.match(
    studioSource,
    /eagleActionControlSessionPath[\s\S]*?source=overview/,
    'the action-control banner on Overview should identify Overview as its return destination',
  );
  assert.match(
    sessionsSource,
    /sourceQuery === ['"]overview['"][\s\S]*?label: ['"]Back to overview['"][\s\S]*?path: `\/agents\/\$\{encodeURIComponent\(agent\.id\)\}`/,
    'sessions opened from the Overview action-control banner should return to the agent Overview',
  );
});

test('landing restores the design-exploration composer and quick-template entry points', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const composerIndex = source.indexOf('className="eva-landing-composer"');
  const quickTemplatesIndex = source.indexOf('aria-label="Quick templates"');

  assert.ok(composerIndex >= 0, 'the design-exploration landing composer should be present');
  assert.ok(quickTemplatesIndex > composerIndex, 'the composer should remain before the quick-template section');
  assert.match(
    source.slice(composerIndex, quickTemplatesIndex),
    /<AiFooter[\s\S]*?onSend=\{handleSend\}[\s\S]*?friendly banking assistant[\s\S]*?voiceActive=\{voiceActive\}/,
    'the landing should reuse the design-exploration composer and example prompt',
  );
  assert.match(
    source,
    /aria-label="quick start with"[\s\S]*?aria-label="Quick templates"[\s\S]*?starterPrompts\.slice\(0,\s*4\)\.map/,
    'the four design-exploration starters should appear below the Quick start with divider',
  );
  assert.match(
    source,
    /onClick=\{\(\) => handleTemplateSelect\(prompt\.templateId\)\}/,
    'each starter should retain the original direct template flow',
  );
  assert.match(
    source,
    />\s*All agents\s*<[\s\S]*?>\s*Start from scratch\s*</,
    'the original secondary landing actions should remain available',
  );
});

test('configuration recommendation actions use the requested visual hierarchy', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');

  assert.doesNotMatch(
    source,
    /className="eva-family-recommendation__header"[\s\S]{0,180}<Badge/,
    'the Recommended next steps heading makes per-card requirement tags redundant',
  );
  assert.match(
    source,
    /<Button variant="secondary" onClick=\{handleReviewPreviewAction\}>\s*Preview\s*<\/Button>/,
    'Preview should remain secondary to Create Agent',
  );
  const actionsStart = source.indexOf("{visibleSteps.includes('actions')");
  const securityStart = source.indexOf("{visibleSteps.includes('security')", actionsStart);
  assert.ok(actionsStart >= 0 && securityStart > actionsStart);
  assert.doesNotMatch(
    source.slice(actionsStart, securityStart),
    />\s*Not needed\s*</,
    'Actions should move forward with Set up action or Continue to security only',
  );
});

test('landing quick templates use the original direct template flow', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');

  assert.match(
    source,
    /aria-label="Quick templates"[\s\S]*?starterPrompts\.slice\(0,\s*4\)\.map[\s\S]*?onClick=\{\(\) => handleTemplateSelect\(prompt\.templateId\)\}/,
    'the four starter cards should be visible on the homepage and use the direct template handler',
  );
  assert.match(
    source,
    /const handleTemplateSelect[\s\S]*?createOrSelectDraftAgent[\s\S]*?navigate\(`\/agents\/\$\{agent\.id\}\/studio`\)/,
    'choosing a homepage template should continue into the existing agent studio',
  );
});

test('homepage free-form prompts can start and continue the original Acme retail workflow', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const intentSource = readSource('../eva/evaFormConfig.ts');
  const handleSendStart = source.indexOf('const handleSend = (text: string)');
  const handleSendEnd = source.indexOf('const matchTemplateFromText', handleSendStart);
  const handleSendSource = source.slice(handleSendStart, handleSendEnd);

  assert.ok(handleSendStart >= 0 && handleSendEnd > handleSendStart);
  assert.doesNotMatch(
    handleSendSource,
    /Choose one agent area before describing the agent/,
    'the homepage prompt should not be blocked by the removed family chooser',
  );
  assert.match(
    handleSendSource,
    /retailPrototypeStep !== ['"]idle['"][\s\S]*?handleRetailReceptionistStoryAnswer\(text\)[\s\S]*?getVoiceAgentWorkflowIntent\(text\)[\s\S]*?beginRetailReceptionistStory\(voiceAgentIntent\)/,
    'active retail replies and new Acme trigger prompts should route through the original guided flow',
  );
  assert.match(
    source,
    /const beginRetailReceptionistStory[\s\S]*?setFreeChatActive\(true\)[\s\S]*?setRetailPrototypeStep\(['"]discovering['"]\)[\s\S]*?originStep[\s\S]*?retail-channel-choice/,
    'the trigger should open the conversational thread and advance to the channel choice',
  );
  assert.match(
    intentSource,
    /hasStoreSignal[\s\S]*?\\b\(store\|shop\|retail\)\\b[\s\S]*?hasRequestIntent/,
    'shop creation prompts should remain recognized as retail workflow intents',
  );
});

test('logistics requests continue from discovery into the pre-built guided flow', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const handleSendStart = source.indexOf('const handleSend = (text: string)');
  const handleSendEnd = source.indexOf('const matchTemplateFromText', handleSendStart);
  const handleSendSource = source.slice(handleSendStart, handleSendEnd);

  assert.match(
    source,
    /const isLogisticsAgentCreationIntent[\s\S]*?normalized\.includes\('logistics'\)[\s\S]*?normalized\.includes\('reservation'\)/,
    'logistics requests should be recognized without requiring an exact prompt match',
  );
  assert.match(
    handleSendSource,
    /isLogisticsAgentCreationIntent\(normalized\)[\s\S]*?beginLogisticsContactCenterIntake\(\)/,
    'a recognized logistics request should check connected systems before opening the guided flow',
  );
  assert.match(
    source,
    /const beginLogisticsContactCenterIntake[\s\S]*?VIP_LOGISTICS_DISCOVERY_ROWS\.length[\s\S]*?setRetailPrototypeStep\('channel'\)[\s\S]*?retail-channel-choice/,
    'the logistics discovery should continue into the structured channel, name, greeting, knowledge, and action flow',
  );
  assert.match(
    source,
    /title: 'Hours of operation'[\s\S]*?title: 'Inventory System – Food, Beverage'[\s\S]*?title: 'Internal Staffing & Scheduling System'[\s\S]*?title: 'Facilities: Space & Equipment'/,
    'the discovery panel should show the four requested operational-system checks',
  );
  assert.match(
    source,
    /const renderRetailDiscoveryTrace = \(showVipLogisticsTrace: boolean\)[\s\S]*?showVipLogisticsTrace\s*\? VIP_LOGISTICS_DISCOVERY_ROWS\s*:\s*RETAIL_DISCOVERY_ROWS[\s\S]*?Checked operating hours, food and beverage inventory, staffing, and facilities/,
    'the completed discovery trace should reuse the Eagle Green rows and summary',
  );
  assert.match(
    source,
    /renderRetailDiscoveryTrace\(\s*message\.text === VIP_LOGISTICS_WORKFLOW_CONTEXT\.discoveryCompleteText/,
    'the persisted Eagle Green completion message should reopen the matching discovery trace',
  );
  assert.match(
    source,
    /agentName: 'Eagle Green Facilities Agent'/,
    'the guided flow should suggest the requested facilities-focused agent name',
  );
  assert.ok(
    source.includes("welcomeMessage: 'Hi, thanks for calling the Eagle Green Facilities line. I can check event readiness, flag issues, or help you resolve something that\\'s been flagged for you. How can I help?'"),
    'the logistics proposal should use the approved Eagle Green Facilities greeting',
  );
  assert.match(
    source,
    /knowledgeBases:\s*\['Reservation System', 'Inventory System – Food & Beverage'\]/,
    'the logistics flow should start with the requested reservation and food-and-beverage systems',
  );
  assert.match(
    source,
    /const VIP_LOGISTICS_RECOMMENDED_KNOWLEDGE_BASES = \[[\s\S]*?name: 'Internal Staffing & Scheduling System'[\s\S]*?name: 'Facilities: Space & Equipment'/,
    'the logistics flow should recommend the two requested operational knowledge sources',
  );
  assert.match(
    source,
    /const VIP_LOGISTICS_CONNECTED_ACTIONS = \['Check Escalation Status'\][\s\S]*?name: 'Create a Service Ticket'[\s\S]*?provider: 'ServiceNow'[\s\S]*?name: 'Look Up Reservation History'[\s\S]*?provider: 'Salesforce'/,
    'the logistics flow should start with escalation status and recommend the requested ServiceNow and Salesforce actions',
  );
  assert.match(
    source,
    /const beginLogisticsContactCenterIntake[\s\S]*?setSelectedKnowledgeBases\(VIP_LOGISTICS_WORKFLOW_CONTEXT\.knowledgeBases\)[\s\S]*?setSelectedActions\(VIP_LOGISTICS_CONNECTED_ACTIONS\)/,
    'starting a logistics flow should reset inherited generic knowledge and actions',
  );
  assert.doesNotMatch(
    source.slice(source.indexOf('const beginLogisticsContactCenterIntake'), source.indexOf('const handleLandingStarterSelect')),
    /handleAgentFamilySelect/,
    'the logistics flow should not fall back to the open-ended Contact Center intake',
  );
});

test('guided prompts from greeting onward keep a stable centered stop position', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const styles = readSource('../../products/ai-agent-studio/components.css');
  const previewCardStyles = styles.slice(
    styles.indexOf('.eva-retail-preview-card {'),
    styles.indexOf('button.eva-retail-preview-card {'),
  );

  assert.match(
    source,
    /RETAIL_CENTERED_ORIGIN_BY_STEP[\s\S]*?welcome:\s*'retail-welcome-choice'[\s\S]*?knowledge:\s*'retail-knowledge-choice'[\s\S]*?actions:\s*'retail-actions-choice'[\s\S]*?phone:\s*'retail-phone-choice'/,
    'the greeting and each upcoming setup question should share one focus contract',
  );
  assert.match(
    source,
    /'ready-to-preview':\s*'retail-final-actions'/,
    'the completed overview should use the same centered stop position as the guided prompts',
  );
  assert.match(
    source,
    /centeredRetailOrigin\s*=\s*RETAIL_CENTERED_ORIGIN_BY_STEP\[retailPrototypeStep\][\s\S]*?shouldCenterRetailActivePrompt\s*=\s*Boolean\([\s\S]*?centeredRetailOrigin\s*&&[\s\S]*?window\.innerHeight/,
    'the current guided response should scroll to the viewport center when it appears',
  );
  assert.match(
    source,
    /centeredRetailOrigin\s*&&\s*latestAssistantMessage\?\.originStep\s*!==\s*centeredRetailOrigin[\s\S]*?return;/,
    'a step transition should preserve the current position until the next prompt is ready',
  );
  assert.match(
    source,
    /captureRetailTransitionScrollTop[\s\S]*?retailTransitionScrollTopRef\.current\s*=\s*scrollContainer\?\.scrollTop[\s\S]*?willAdvanceCenteredRetailStep[\s\S]*?captureRetailTransitionScrollTop\(\)[\s\S]*?useLayoutEffect[\s\S]*?scrollContainer\.scrollTop\s*=\s*retailTransitionScrollTopRef\.current/,
    'the current scroll position should be restored before paint while a centered-step response is pending',
  );
  assert.match(
    source,
    /const selectRetailPhoneNumber[\s\S]*?captureRetailTransitionScrollTop\(\)[\s\S]*?handleRetailReceptionistStoryAnswer\(phoneValue\)/,
    'choosing a connected number should preserve the phone prompt position until the overview is ready',
  );
  assert.match(
    source,
    /shouldHoldPhoneFocusSpacing[\s\S]*?retailPrototypeStep === 'ready-to-preview'[\s\S]*?evaThinking[\s\S]*?retail-final-actions[\s\S]*?eva-first-interface__free-chat--phone-focus/,
    'the phone step should keep its reserved space throughout the transition to the overview',
  );
  assert.match(
    source,
    /phoneMenu[\s\S]*?eva-retail-phone-selector__menu[\s\S]*?phoneMenu\.getBoundingClientRect\(\)\.bottom[\s\S]*?composer\.getBoundingClientRect\(\)\.top/,
    'opening the connected-number menu should scroll it clear of the composer',
  );
  assert.match(
    source,
    /hasCenteredRetailPrompt[\s\S]*?shouldHoldActiveRetailPromptPosition[\s\S]*?evaThinking\s*&&\s*hasCenteredRetailPrompt[\s\S]*?eva-first-interface__free-chat--active-prompt-focus/,
    'the active guided step should retain its focus spacing while the next response is generated',
  );
  assert.match(
    styles,
    /\.eva-first-interface__free-chat--active-prompt-focus[\s\S]*?padding-bottom:\s*clamp\(280px, 42vh, 520px\)/,
    'active prompts should reserve enough trailing space for centering',
  );
  assert.match(
    styles,
    /\.eva-first-interface__free-chat--phone-focus[\s\S]*?padding-bottom:\s*clamp\(360px, 50vh, 600px\)/,
    'the phone step should reserve enough space for its open menu above the composer',
  );
  assert.match(
    styles,
    /\.eva-first-interface__free-chat[\s\S]*?overflow-anchor:\s*none/,
    'browser scroll anchoring should not move the prompt while response content is appended',
  );
  assert.doesNotMatch(
    source,
    /meta: '(?:San Francisco|Austin|San Jose) store'/,
    'connected phone-number locations should not repeat the word store',
  );
  assert.match(
    previewCardStyles,
    /width:\s*min\(100%, 332px\)/,
    'the final overview should retain its original compact card width',
  );
  assert.doesNotMatch(
    previewCardStyles,
    /min-width:\s*100%/,
    'the final overview card should not stretch to the full response width',
  );
});

test('Contact Center proposal review shows the verified channel, name, greeting, and instructions', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const proposalStart = source.indexOf('className="eva-family-proposal"');
  const proposalEnd = source.indexOf('className="eva-family-proposal__actions"', proposalStart);

  assert.ok(proposalStart >= 0 && proposalEnd > proposalStart, 'the family proposal card should be present');
  const proposalSource = source.slice(proposalStart, proposalEnd);
  for (const label of ['Channel', 'Name', 'Greeting', 'Instructions']) {
    assert.match(
      proposalSource,
      new RegExp(`<dt>${label}<\\/dt>`),
      `the proposal should let the user verify ${label.toLowerCase()}`,
    );
  }

  const applyStart = source.indexOf('const applyProposalToConfiguration');
  const applyEnd = source.indexOf('const handleAgentFamilySelect', applyStart);
  const applySource = source.slice(applyStart, applyEnd);
  assert.match(applySource, /proposal\.selectedChannels/);
  assert.match(applySource, /setSelectedChannels\(/);
  assert.match(
    applySource,
    /setWelcomeMessage\(proposal\.greeting\)/,
    'applying the reviewed proposal should preserve its greeting instead of regenerating one',
  );
});

test('Contact Center intake reuses the Acme option and verification card patterns', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const styles = readSource('../../products/ai-agent-studio/components.css');

  assert.match(
    source,
    /const CONTACT_CENTER_INTAKE_CHANNEL_OPTIONS = \[[\s\S]*?label:\s*['"]Voice['"][\s\S]*?label:\s*['"]Digital['"][\s\S]*?label:\s*['"]Video['"]/,
  );
  assert.match(
    source,
    /isContactCenterChannelPrompt[\s\S]*?<Card[\s\S]*?role="checkbox"[\s\S]*?setContactCenterSelectedChannels[\s\S]*?>\s*Continue\s*</,
    'channel selection should use the existing selectable Acme cards',
  );
  assert.match(
    source,
    /isContactCenterNamePrompt[\s\S]*?className="eva-retail-agent-name-options"[\s\S]*?>\s*Edit name\s*<[\s\S]*?>\s*Use edited name\s*</,
    'the suggested name should reuse the existing accept-or-edit layout',
  );
  assert.match(
    source,
    /isContactCenterGreetingPrompt[\s\S]*?className="eva-retail-welcome-options"[\s\S]*?>\s*Accept greeting\s*<[\s\S]*?>\s*Edit greeting\s*</,
    'the opening greeting should reuse the existing accept-or-edit card',
  );
  assert.match(styles, /\.eva-retail-channel-option\.card\s*\{/);
  assert.match(styles, /\.eva-retail-agent-name-options\s*\{/);
  assert.match(styles, /\.eva-retail-welcome-option\s*\{/);
});

test('family intake uses the established thinking interval before each assistant reply', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const responseSource = readSource('../../components/shared/ai/AiResponseMessage.jsx');
  const styles = readSource('../../products/ai-agent-studio/components.css');
  const timerStart = source.indexOf('const addOnboardingAssistantMessage');
  const timerEnd = source.indexOf('const applyProposalToConfiguration', timerStart);
  const familySelectStart = source.indexOf('const handleAgentFamilySelect');
  const familySelectEnd = source.indexOf('const handleLandingStarterSelect', familySelectStart);
  const answerStart = source.indexOf('const handleFamilyIntakeAnswer');
  const answerEnd = source.indexOf('const handleAskForProposalChanges', answerStart);

  assert.match(
    source.slice(timerStart, timerEnd),
    /setEvaThinking\(true\)[\s\S]*?window\.setTimeout\([\s\S]*?setEvaThinking\(false\)[\s\S]*?,\s*850\)/,
  );
  assert.match(source.slice(familySelectStart, familySelectEnd), /addOnboardingAssistantMessage\(/);
  assert.ok(
    [...source.slice(answerStart, answerEnd).matchAll(/addOnboardingAssistantMessage\(/g)].length >= 3,
    'invalid answers, subsequent questions, and the proposal should all wait before replying',
  );
  assert.match(
    source,
    /\{evaThinking\s*&&\s*\([\s\S]*?assistantName="AI Assistant is thinking\.\.\."[\s\S]*?assistantState="processing"/,
  );
  assert.match(
    source,
    /isFamilyIntakePrompt\s*&&\s*\(!isLatestFamilyIntakePrompt\s*\|\|\s*evaThinking\)/,
    'the previous prompt controls should be hidden while its next reply is being prepared',
  );
  assert.match(responseSource, /import aiSimplifiedAnimationUrl from ['"].*ai simplified\.json\?url['"]/);
  assert.match(
    responseSource,
    /function AiGeneratingIcon\(\)[\s\S]*?lottie\.loadAnimation\([\s\S]*?loop:\s*true,[\s\S]*?path:\s*aiSimplifiedAnimationUrl/,
    'the wait state should reuse the animated AI icon from the Acme creation flow',
  );
  assert.match(
    styles,
    /\.app--ai \.eva-first-interface__free-chat \.ai-response__generating-icon\s*\{\s*display:\s*inline-flex;/,
    'the shared animated icon should remain visible during conversational family intake',
  );
});

test('starter proposal actions edit the plan, create a draft, or continue to its overview', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const handlerStart = source.indexOf('const saveFamilyProposalDraft');
  const handlerEnd = source.indexOf('const handleCreateAgent', handlerStart);
  const handlerSource = source.slice(handlerStart, handlerEnd);

  assert.match(
    source,
    /onClick=\{\(\)\s*=>\s*setFamilyProposalEditing\(true\)\}[\s\S]*?>\s*Edit plan\s*<\/Button>/,
  );
  assert.match(
    source,
    /onClick=\{handleCreateFamilyAgent\}[\s\S]*?>\s*Create agent\s*<\/Button>/,
  );
  assert.match(
    source,
    /onClick=\{handleContinueFamilyConfiguration\}[\s\S]*?>\s*Continue configuration\s*<\/Button>/,
  );
  assert.match(
    handlerSource,
    /const handleCreateFamilyAgent[\s\S]*?saveFamilyProposalDraft\(\)[\s\S]*?setVariation\(['"]dashboard['"]\)[\s\S]*?navigate\(['"]\/agents['"]\)/,
    'Create agent should save the proposal as a draft and return to All Agents',
  );
  assert.match(
    handlerSource,
    /const handleContinueFamilyConfiguration[\s\S]*?saveFamilyProposalDraft\(\)[\s\S]*?navigate\(`\/agents\/\$\{agent\.id\}\/studio`\)/,
    'Continue configuration should save the draft and open its overview',
  );
  assert.doesNotMatch(source, />\s*(Apply draft|Ask for changes|Configure more)\s*</);

  const instructionsStart = source.indexOf("{visibleSteps.includes('instructions')");
  const knowledgeStart = source.indexOf("{visibleSteps.includes('knowledge')", instructionsStart);
  assert.ok(instructionsStart >= 0 && knowledgeStart > instructionsStart, 'the Instructions section should be present');
  assert.match(
    source.slice(instructionsStart, knowledgeStart),
    /renderRankedNextStepsAfter\(['"]instructions['"]\)/,
    'ranked recommendations should be visible without making the user jump ahead to Review',
  );
  assert.match(
    source,
    /onClick=\{\(\)\s*=>\s*openRecommendationSection\(recommendation\.targetSection,\s*recommendation\.id\)\}[\s\S]*?\{getRecommendationActionLabel\(recommendation\)\}/,
    'the recommendation-specific action should open the section named by the recommendation',
  );
});

test('recommendation actions use concise labels that describe their destination', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const labelStart = source.indexOf('const getRecommendationActionLabel');
  const labelEnd = source.indexOf('type EvaVoicePreviewSocketMessage', labelStart);
  const labelSource = source.slice(labelStart, labelEnd);

  assert.ok(labelStart >= 0 && labelEnd > labelStart);
  assert.match(labelSource, /actionKind === ['"]open_external['"][\s\S]*?return ['"]Connect['"]/);
  assert.match(labelSource, /case ['"]actions['"]:[\s\S]*?case ['"]handoff['"]:[\s\S]*?return ['"]Add action['"]/);
  assert.match(labelSource, /case ['"]knowledge['"]:[\s\S]*?return ['"]Add knowledge['"]/);
  assert.match(labelSource, /case ['"]identity['"]:[\s\S]*?return ['"]Add identity check['"]/);
  assert.match(labelSource, /case ['"]security['"]:[\s\S]*?case ['"]audit['"]:[\s\S]*?return ['"]Review security['"]/);
  assert.match(labelSource, /case ['"]preview['"]:[\s\S]*?case ['"]testing['"]:[\s\S]*?return ['"]Test agent['"]/);
  assert.doesNotMatch(
    source,
    /recommendation\.actionKind === ['"]open_external['"] \? ['"]Connect['"] : ['"]Set up['"]/,
  );
});

test('Recommended next steps owns a dynamic Next action that opens the first unresolved item', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const navigatorStart = source.indexOf('const handleNextRecommendedStep =');
  const recommendationsStart = source.indexOf('const renderRankedNextSteps =');
  const recommendationsEnd = source.indexOf('const renderRankedNextStepsAfter', recommendationsStart);
  const navigatorSource = source.slice(navigatorStart, recommendationsEnd);
  const recommendationsSource = source.slice(recommendationsStart, recommendationsEnd);
  const channelsStart = source.indexOf("{visibleSteps.includes('channels')");
  const instructionsStart = source.indexOf("{visibleSteps.includes('instructions')", channelsStart);
  const channelsSource = source.slice(channelsStart, instructionsStart);

  assert.ok(navigatorStart >= 0 && recommendationsStart > navigatorStart && recommendationsEnd > recommendationsStart);
  assert.match(
    navigatorSource,
    /const nextRecommendation = activeAgentRecommendations\[0\][\s\S]*?const isFinalRecommendation = activeAgentRecommendations\.length === 1[\s\S]*?dismissRecommendation\(activeDraftAgentId,\s*nextRecommendation\.id\)[\s\S]*?openRecommendationSection\([\s\S]*?nextRecommendation\.targetSection,[\s\S]*?undefined,[\s\S]*?isFinalRecommendation,[\s\S]*?\)/,
    'Next should consume the first visible recommendation before opening its destination',
  );
  assert.match(
    recommendationsSource,
    /className="eva-dialogue__actions eva-next-step-block__actions"[\s\S]*?onClick=\{handleNextRecommendedStep\}[\s\S]*?>\s*Next\s*</,
    'the navigator should keep one compact Next action inside the recommendation container',
  );
  assert.doesNotMatch(recommendationsSource, /setEvaStep\(['"]knowledge['"]\)/);
  assert.match(
    channelsSource,
    /evaStep === ['"]channels['"]\s*&&\s*!shouldRenderRankedNextStepsAfter\(['"]channels['"]\)[\s\S]*?Continue to instructions/,
    'the fixed channel continuation should disappear whenever the recommendation navigator is visible',
  );
});

test('guided recommendation surfaces share the configuration form measure', () => {
  const styles = readSource('../../products/ai-agent-studio/components.css');

  assert.match(
    styles,
    /\.eva-first-interface--generated:not\(\.eva-first-interface--free-chat\) \.eva-dialogue > \.eva-next-step-block,\s*\.eva-first-interface--generated:not\(\.eva-first-interface--free-chat\) \.eva-dialogue > \.eva-recommendation-review-actions\s*\{[\s\S]*?width:\s*min\(100%,\s*960px\);[\s\S]*?margin-inline:\s*auto;/,
    'ranked recommendations and the review handoff should align to the same centered 960px measure as the guided configuration response',
  );
});

test('entering evaluation removes the preview handoff actions before rendering the scenario builder', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const styles = readSource('../../products/ai-agent-studio/components.css');
  const previewStart = source.indexOf("{visibleSteps.includes('preview')");
  const testingStart = source.indexOf("{visibleSteps.includes('testing')", previewStart);
  const previewSource = source.slice(previewStart, testingStart);

  assert.ok(previewStart >= 0 && testingStart > previewStart);
  assert.match(
    previewSource,
    /\{evaStep !== ['"]testing['"] && \([\s\S]*?className="eva-dialogue__actions"[\s\S]*?Evaluate my agent[\s\S]*?Save changes/,
    'the preview handoff row should disappear once evaluation is active so the scenario builder moves up',
  );
  assert.match(
    source,
    /className=\{`eva-dialogue\$\{evaStep === ['"]testing['"] \? ['"] eva-dialogue--testing-active['"] : ['"]['"]\}`\}/,
    'the active evaluation should identify the configuration scroll surface',
  );
  assert.match(
    styles,
    /\.eva-generated-layout__main > \.eva-dialogue\.eva-dialogue--testing-active\s*\{[\s\S]*?padding-bottom:\s*calc\(100vh - 120px\);/,
    'evaluation should reserve enough trailing scroll space to align the scenario question at the top',
  );
});

test('ranked next steps follow the selected setup section until the journey is resolved', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const contextSource = readSource('../../contexts/AppContext.tsx');
  const sessionSource = readSource('../eva/evaFormConfig.ts');
  const openStart = source.indexOf('const openRecommendationSection');
  const openEnd = source.indexOf('const refreshDraftBasics', openStart);
  const openSource = source.slice(openStart, openEnd);
  const dismissStart = contextSource.indexOf('const dismissRecommendation');
  const dismissEnd = contextSource.indexOf('const regenerateAgentRecommendations', dismissStart);
  const dismissSource = contextSource.slice(dismissStart, dismissEnd);

  assert.match(openSource, /audit:\s*['"]security['"]/);
  assert.match(
    openSource,
    /setRecommendationAnchorStep\(resolvedStep\)[\s\S]*setRecommendationPendingId\(recommendationId\s*\?\?\s*null\)[\s\S]*setEvaStep\(resolvedStep\)/,
  );
  assert.match(
    source,
    /recommendationJourneyIds\s*\.map\([\s\S]*?actionableAgentRecommendations\.find/,
    'the initial three-item journey should stay frozen instead of backfilling a fourth item',
  );
  assert.match(
    source,
    /familyConfiguration\.audience\s*=\s*\{[\s\S]*?progress:\s*audience\.trim\(\)\s*\?\s*['"]configured['"]\s*:\s*['"]not_started['"]/,
    'the verified audience should be resolved before the initial three recommendations are ranked',
  );
  assert.match(
    source,
    /familyConfiguration\.placement\s*=\s*\{[\s\S]*?progress:\s*internalPlacements\.length\s*>\s*0\s*\?\s*['"]configured['"]\s*:\s*['"]not_started['"]/,
    'the default employee placement should not displace Actions from the frozen recommendation journey',
  );
  assert.match(source, /if\s*\(activeAgentRecommendations\.length\s*===\s*0\)\s*\{\s*return null;/);
  assert.match(
    source,
    /const shouldRenderRankedNextStepsAfter[\s\S]*?recommendationAnchorStep\s*!==\s*step[\s\S]*?recommendationPendingId[\s\S]*?const renderRankedNextStepsAfter[\s\S]*?shouldRenderRankedNextStepsAfter\(step\)[\s\S]*?renderRankedNextSteps\(\)/,
  );
  assert.match(
    source,
    /if\s*\(!recommendationPendingId\s*\|\|\s*evaStep\s*===\s*recommendationAnchorStep\)\s*return;[\s\S]*?setRecommendationPendingId\(null\);[\s\S]*?setRecommendationAnchorStep\(evaStep\);/,
    'leaving an unresolved setup section should restore the remaining recommendation dock at the new step',
  );
  assert.equal((source.match(/aria-label="Ranked next steps"/g) ?? []).length, 1);

  for (const step of [
    'profile',
    'channels',
    'instructions',
    'knowledge',
    'actions',
    'security',
    'review',
    'preview',
    'testing',
  ]) {
    assert.match(source, new RegExp(`renderRankedNextStepsAfter\\(['"]${step}['"]\\)`));
  }

  assert.match(sessionSource, /recommendationJourneyIds\?:\s*string\[\]/);
  assert.match(sessionSource, /recommendationAnchorStep\?:\s*EvaConversationStep/);
  assert.match(sessionSource, /recommendationPendingId\?:\s*string\s*\|\s*null/);
  assert.match(sessionSource, /recommendationReviewStep\?:\s*EvaConversationStep\s*\|\s*null/);
  assert.match(
    source,
    /const completeRecommendationJourney = \(\) => \{[\s\S]*?setRecommendationReviewStep\(null\);[\s\S]*?setRecommendationAnchorStep\(['"]review['"]\);[\s\S]*?setEvaStep\(['"]review['"]\);/,
    'finishing the last navigator task should hand the user to Review',
  );
  assert.match(
    source,
    /const renderRecommendationReviewHandoff[\s\S]*?Continue to review/,
    'non-security recommendation destinations should expose a direct Review handoff',
  );
  assert.match(
    source,
    /shouldRouteRecommendationJourneyToReview\(['"]security['"]\)[\s\S]*?completeRecommendationJourney\(\)/,
    'the Security completion action should also finish the journey at Review',
  );
  assert.match(
    source,
    /setActiveDraftAgentId\(null\);[\s\S]*?setRecommendationJourneyAgentId\(null\);[\s\S]*?setRecommendationJourneyIds\(\[\]\);[\s\S]*?setRecommendationAnchorStep\(['"]instructions['"]\);[\s\S]*?setRecommendationPendingId\(null\);[\s\S]*?setRecommendationReviewStep\(null\);/,
    'a new thread should not reuse recommendation journey state from the previous agent',
  );
  assert.match(
    dismissSource,
    /dismissedRecommendationIds:\s*\[\.\.\.draft\.dismissedRecommendationIds,\s*recommendationId\]/,
  );
  assert.match(
    dismissSource,
    /recommendations:\s*draft\.recommendations\.filter\(item => item\.id !== recommendationId\)/,
  );
});

test('guided configuration toolbar restores summary, progress, and save actions', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const controlsStart = source.indexOf('<div className="eva-view-actions__controls">');
  const controlsEnd = source.indexOf('</div>', controlsStart);

  assert.ok(controlsStart >= 0 && controlsEnd > controlsStart, 'the guided configuration toolbar should be present');
  const controlsSource = source.slice(controlsStart, controlsEnd);

  assert.match(controlsSource, /onClick=\{handleViewSummary\}/);
  assert.match(controlsSource, /aria-label="View agent summary"/);
  assert.match(controlsSource, /name="meeting-summary"/);
  assert.match(controlsSource, /setShowEvaGeneratedSidePanel\(previous\s*=>\s*!previous\)/);
  assert.match(controlsSource, /Collapse progress sidebar/);
  assert.match(controlsSource, /Expand progress sidebar/);
  assert.match(controlsSource, /aria-expanded=\{showEvaGeneratedSidePanel\}/);
  assert.match(controlsSource, /aria-controls="eva-generated-progress-sidebar"/);
  assert.match(controlsSource, /name="side-panel"/);
  assert.match(
    controlsSource,
    /onClick=\{configurationMode === ['"]edit['"] \? handleSaveConfigurations : handleCreateAgent\}[\s\S]*?Save changes[\s\S]*?Create Agent/,
  );
  assert.doesNotMatch(controlsSource, /Create new agent/);
  assert.doesNotMatch(controlsSource, /Publish version/);

  const saveHandlerStart = source.indexOf('const handleSaveConfigurations');
  const saveHandlerEnd = source.indexOf('const enterRetailAgentStudio', saveHandlerStart);
  const saveHandlerSource = source.slice(saveHandlerStart, saveHandlerEnd);
  assert.match(saveHandlerSource, /persistEvaSession\(/);
  assert.match(saveHandlerSource, /updateAgentDraft\(activeDraftAgentId,\s*current\s*=>\s*current\)/);
  assert.match(
    saveHandlerSource,
    /setVariation\(['"]dashboard['"]\)[\s\S]*?navigate\(['"]\/agents['"]\)/,
    'saving an existing configuration should return to the all-agents view',
  );
  assert.match(saveHandlerSource, /showToast\(['"]Changes saved\./);
  assert.match(source, /id="eva-generated-progress-sidebar"/);
});

test('existing agents progressively disclose untouched optional configuration', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const styles = readSource('../../products/ai-agent-studio/components.css');

  assert.match(
    source,
    /const \[generatedChatPanelMode,\s*setGeneratedChatPanelMode\] = useState<GeneratedChatPanelMode>\(\s*configurationMode === ['"]edit['"] \? ['"]collapsed['"] : ['"]rail['"],?\s*\);/,
    'reopening an existing agent should default the conversation rail to collapsed',
  );
  assert.match(
    source,
    /const progressivelyDisclosedSteps = new Set<EvaConversationStep>\(\[[\s\S]*?['"]channels['"][\s\S]*?['"]knowledge['"][\s\S]*?['"]actions['"][\s\S]*?['"]security['"][\s\S]*?\]\);/,
    'optional configuration sections should use progressive disclosure',
  );
  assert.match(
    source,
    /familyStepOrder[\s\S]*?\.slice\(0,\s*visibleStepIndex \+ 1\)[\s\S]*?\.filter\(step => \{[\s\S]*?step === evaStep[\s\S]*?progress !== undefined && progress !== ['"]not_started['"]/,
    'edit mode should show an optional section only when it is active or has recorded progress',
  );
  assert.match(
    styles,
    /\.eva-generated-layout__main > \.eva-dialogue\s*\{[\s\S]*?height:\s*100%;[\s\S]*?min-height:\s*0;[\s\S]*?overflow-y:\s*auto;/,
    'the configuration workspace should own a full-height vertical scroll surface',
  );
});

test('Knowledge setup lists every ready collection from the shared knowledge inventory', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const serviceSource = readSource('../../services/knowledgeService.ts');
  const knowledgeStart = source.indexOf("{visibleSteps.includes('knowledge')");
  const actionsStart = source.indexOf("{visibleSteps.includes('actions')", knowledgeStart);

  assert.ok(knowledgeStart >= 0 && actionsStart > knowledgeStart, 'the Knowledge setup section should be present');
  const knowledgeSource = source.slice(knowledgeStart, actionsStart);

  assert.match(source, /import \{ listReadyCollections \} from ['"]\.\.\/\.\.\/services\/knowledgeService['"]/);
  assert.match(source, /listReadyCollections\(\)[\s\S]*?setAvailableKnowledgeBases/);
  assert.match(knowledgeSource, /knowledgeBaseOptions\.map\(source =>/);
  assert.match(knowledgeSource, /loading=\{availableKnowledgeBases === null\}/);
  assert.match(knowledgeSource, /Knowledge bases could not be loaded/);
  assert.match(knowledgeSource, /label: ['"]Retry['"]/);
  assert.match(knowledgeSource, /ready to enable/);
  assert.doesNotMatch(knowledgeSource, /blank organization|No recommended knowledge sources/);
  assert.match(serviceSource, /source\.status === ['"]processed['"]/);
  assert.match(serviceSource, /name: ['"]Customer Support['"]/);
  assert.match(serviceSource, /name: ['"]Technical Support['"]/);
});

test('final creation actions publish once and return to the existing-agent list', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const handlerStart = source.indexOf('const handleCreateAgent');
  const handlerEnd = source.indexOf('const openRecommendationSection', handlerStart);
  const handlerSource = source.slice(handlerStart, handlerEnd);

  assert.ok(handlerStart >= 0 && handlerEnd > handlerStart);
  assert.match(handlerSource, /getMinimumPublishIssues\(draftToPublish\)/);
  assert.match(handlerSource, /publishAgentVersion\(activeDraftAgentId\)/);
  assert.match(handlerSource, /setVariation\(['"]dashboard['"]\)/);
  assert.match(handlerSource, /navigate\(['"]\/agents['"]\)/);
  assert.match(handlerSource, /removeItem\(EVA_SESSION_STORAGE_KEY\)/);
  assert.match(handlerSource, /removeItem\(EVA_AUTO_START_VOICE_PREVIEW_KEY\)/);
  assert.doesNotMatch(source, /handlePublishCurrentVersion/);
});

test('create versus edit mode keeps both primary configuration actions synchronized', () => {
  const source = readSource('../eva/EvaChatExperience.tsx');
  const landingSource = readSource('../../pages/agent/AgentStudioLanding.tsx');
  const listSource = readSource('../eva/EvaAgentsTable.tsx');
  const dynamicActionPattern =
    /variant="primary"[\s\S]{0,180}onClick=\{configurationMode === ['"]edit['"] \? handleSaveConfigurations : handleCreateAgent\}[\s\S]{0,180}\{configurationMode === ['"]edit['"] \? ['"]Save changes['"] : ['"]Create Agent['"]\}/g;

  assert.ok(
    [...source.matchAll(dynamicActionPattern)].length >= 4,
    'top, Review, Preview, and post-test actions should share the same mode-aware primary CTA',
  );
  assert.match(source, /const \[configurationMode, setConfigurationMode\] = useState<['"]create['"] \| ['"]edit['"]>/);
  assert.match(source, /configurationMode,\s*landingMode/);
  assert.match(landingSource, /configurationMode: ['"]edit['"]/);
  assert.match(listSource, /configurationMode: ['"]edit['"]/);

  const saveHandlerStart = source.indexOf('const handleSaveConfigurations');
  const saveHandlerEnd = source.indexOf('const enterRetailAgentStudio', saveHandlerStart);
  const saveHandlerSource = source.slice(saveHandlerStart, saveHandlerEnd);
  assert.match(saveHandlerSource, /updateAgentDraft\(activeDraftAgentId,\s*current\s*=>\s*current\)/);
  assert.match(saveHandlerSource, /setVariation\(['"]dashboard['"]\)/);
  assert.match(saveHandlerSource, /navigate\(['"]\/agents['"]\)/);
  assert.doesNotMatch(saveHandlerSource, /publishAgentVersion|navigateToAgentStudio/);
});

test('AI agent list cards keep a visible 16px grid gap', () => {
  const styles = readSource('../../components.css');
  const spacingTokens = readSource('../../tokens/spacing-tokens.css');
  const gridRuleStart = styles.indexOf('.ai-agents-grid {');
  const gridRuleEnd = styles.indexOf('}', gridRuleStart);
  const cardRuleStart = styles.indexOf('.ai-agents-agent-card {');
  const cardRuleEnd = styles.indexOf('}', cardRuleStart);

  assert.ok(gridRuleStart >= 0 && gridRuleEnd > gridRuleStart);
  assert.ok(cardRuleStart >= 0 && cardRuleEnd > cardRuleStart);
  assert.match(styles.slice(gridRuleStart, gridRuleEnd), /gap:\s*var\(--spacing-small\)/);
  assert.match(spacingTokens, /--spacing-small:\s*16px/);
  assert.doesNotMatch(
    styles.slice(cardRuleStart, cardRuleEnd),
    /max-width:/,
    'cards must fill their grid tracks so extra track width does not inflate the visible gap',
  );
});

test('AI agent list imports the design-variation hook it invokes', () => {
  const source = readSource('../eva/EvaAgentsTable.tsx');

  assert.match(
    source,
    /import \{ useDesignVariation \} from ['"]\.\.\/\.\.\/contexts\/DesignVariationContext['"];?/,
  );
  assert.match(source, /const \{ setVariation \} = useDesignVariation\(\);/);
});

test('Dashboard home starts the first conversational creation landing', () => {
  const dashboardSource = readSource('../../pages/Dashboard.tsx');
  const sidebarSource = readSource('../../products/ai-agent-studio/components/Sidebar.tsx');

  assert.match(dashboardSource, /<EvaChatExperience resetSessionOnInitialMount \/>/);
  assert.match(sidebarSource, /\{\s*path:\s*['"]\/['"],\s*label:\s*['"]New agent['"]/);
  assert.doesNotMatch(sidebarSource, /\{\s*path:\s*['"]\/['"],\s*label:\s*['"]Dashboard['"]/);
  assert.match(sidebarSource, /item\.path === ['"]\/['"][\s\S]*?setVariation\(['"]dashboard['"]\)/);
  assert.match(sidebarSource, /navigate\(item\.path\)/);
  assert.match(
    sidebarSource,
    /agentsRouteShowsBuildingExperience[\s\S]*?location\.pathname === '\/agents\/eva-canvas'[\s\S]*?location\.pathname === '\/agents'[\s\S]*?variation !== 'dashboard' \|\| !hasFamilyAgents/,
    'creation experiences rendered under an agents route should still belong to New agent navigation',
  );
  assert.match(
    sidebarSource,
    /item\.path === '\/'[\s\S]*?isNewAgentActive[\s\S]*?item\.path === '\/agents'[\s\S]*?!agentsRouteShowsBuildingExperience && isActive\(item\.path\)/,
    'New agent and AI Agents should never both be selected while the builder is active',
  );
});
