import type { IconName } from './types';

export interface IconCategory {
  id: string;
  label: string;
  icons: IconName[];
}

export const ICON_CATEGORIES: IconCategory[] = [
  {
    id: 'action',
    label: 'Action',
    icons: [
      'add-option', 'add-photo', 'add-poll', 'add-question', 'add-video-marker',
      'approval-pending', 'approvals', 'archive', 'assign-host', 'assign-privilege',
      'auto-answer', 'auto-detection', 'backup-data', 'bookmark', 'cancel',
      'check', 'check-circle', 'clean-up', 'clear', 'close-space',
      'completed-by-base', 'completed-by-time', 'completed-interaction',       'copy', 'crop',
      'decline', 'delete', 'done-all', 'download',
      'draft', 'drag', 'dragger-horizontal', 'dragger-vertical', 'edit',
      'editable-partial', 'enter', 'eraser', 'exclude', 'exit-room',
      'export', 'favorite', 'favorites', 'filter', 'filter-circle',
      'flag', 'flag-circle', 'follow-up', 'fulfillment', 'hide',
      'import', 'include', 'launch', 'like', 'link',
      'mark-as-unread', 'minus', 'more', 'more-adr', 'more-circle',
      'open-in-folder', 'open-pages', 'pass-mouse', 'pin', 'pin-list',
      'pin-list-activity', 'pin-muted', 'placeholder', 'plus', 'plus-circle',
      'prevent-download', 'print', 'purchase-order', 'reactivate', 'redo',
      'refresh', 'remove', 'reset', 'restart', 'save',
      'scan', 'search', 'select-all', 'selection', 'send',
      'share-screen', 'share-screen-add', 'share-space', 'shopping-cart',
      'sort-ascending', 'sort-descending', 'stop', 'stop-circle', 'tag',
      'undo', 'unlink', 'unread', 'unsorted', 'update-file-share',
      'upload', 'upload-image', 'zoom-in', 'zoom-out',
    ],
  },
  {
    id: 'ai',
    label: 'AI',
    icons: [
      'alternate-response', 'automation', 'bot', 'bot-customer-assistant',
      'bot-expert-assistant', 'color-meeting-summary', 'color-prompts-ai',
      'color-schedule-ai', 'color-search-ai', 'color-sparkle', 'color-summarize-ai',
      'intelligent-routing', 'magic-pen', 'meeting-summary', 'prompts-ai',
      'schedule-ai', 'search-ai', 'smart-audio', 'smart-reply', 'sparkle',
      'summarize-ai',
    ],
  },
  {
    id: 'alerts',
    label: 'Alerts',
    icons: [
      'alarm', 'alert', 'alert-active', 'alert-muted', 'announcement',
      'announcement-muted', 'error-legacy', 'exclamation', 'info-circle',
      'info-circle-two', 'priority-circle', 'priority-circle-two', 'priority-wave',
      'warning',
    ],
  },
  {
    id: 'audio-video',
    label: 'Audio & Video',
    icons: [
      'adjust-audio', 'adjust-microphone', 'adjust-video', 'advanced-noise-removal',
      'audio-broadcast', 'audio-call', 'audio-enhancement', 'audio-only', 'audio-opt-all',
      'callrate', 'camera', 'camera-aux', 'camera-muted', 'camera-on',
      'camera-photo', 'camera-swap', 'capture-rewind', 'closed-caption-badge',
      'closed-captions', 'content-share', 'fast-forward', 'fbw', 'ffw',
      'forward-ten-sec', 'fullscreen', 'fullscreen-exit', 'headphones', 'headphones-muted',
      'join-audio', 'media-player', 'media-quality-good', 'media-quality-poor',
      'media-quality-poor-colored', 'media-quality-unstable', 'media-quality-unstable-colored',
      'microphone', 'microphone-hard-muted', 'microphone-music-mode',
      'microphone-music-mode-on', 'microphone-muted', 'microphone-on',
      'microphone-opt-all', 'microphone-opt-all-muted', 'microphone-opt-all-on',
      'microphone-opt-me', 'microphone-opt-me-muted', 'microphone-opt-me-on',
      'multimedia', 'music-mode-circle', 'music-note', 'mute-on-entry',
      'noise-removal', 'pause', 'play', 'play-circle', 'record',
      'record-active', 'record-paused', 'receive-voice', 'rewind-ten-sec',
      'ringtone', 'send-voice', 'skip', 'skip-bw', 'skip-fw',
      'sound-default', 'speaker', 'speaker-disconnected', 'speaker-muted',
      'speaker-off', 'speaker-on', 'speaker-turn-down', 'speaker-turn-up',
      'stop-content-share', 'streaming', 'studio-mode', 'two-way-voice-stream',
      'video', 'video-blur', 'video-effect', 'video-layout', 'video-layout-custom',
      'video-layout-equal', 'video-layout-equal-dual', 'video-layout-overlay',
      'video-layout-presentation', 'video-layout-presenter-dominant',
      'video-layout-prominent', 'video-layout-share-dominant', 'video-layout-single',
      'video-layout-speaker', 'video-layout-stack', 'video-layout-video-dominant',
      'video-plus', 'video-speaker-track',
    ],
  },
  {
    id: 'brand',
    label: 'Brand',
    icons: [
      'apple', 'bitmoji-connect', 'bitmoji-connected', 'webex-board',
      'webex-codec-plus', 'webex-desk-camera', 'webex-helix', 'webex-meetings',
      'webex-quad-camera', 'webex-room-kit', 'webex-room-kit-plus', 'webex-share',
      'webex-teams', 'webex-teams-new', 'webex-teams-remove',
    ],
  },
  {
    id: 'chat',
    label: 'Chat',
    icons: [
      'chat', 'chat-group', 'chat-mute', 'commenting', 'external-message',
      'forward-message', 'gif', 'gif-horizontal', 'mention', 'message-queing',
      'reply', 'reply-list', 'reply-privately', 'sms-inbound', 'sms-message',
      'sms-message-outgoing', 'sms-message-start', 'sms-unread', 'start-chat',
      'stickers',
    ],
  },
  {
    id: 'communication',
    label: 'Communication',
    icons: [
      'analog-headset', 'attendant-console', 'blind-transfer', 'call-barge',
      'call-barge-silent', 'call-forward-settings', 'call-group-pickup',
      'call-handling', 'call-hold', 'call-incoming', 'call-list', 'call-merge',
      'call-missed', 'call-more', 'call-outgoing', 'call-pickup',
      'call-pickup-other', 'call-private', 'call-remote', 'call-request',
      'call-return', 'call-room', 'call-settings', 'call-split', 'call-swap',
      'call-voicemail', 'campaign-management', 'channel-ussd', 'concierge',
      'dect-handset', 'dialpad', 'emergency-callback-number', 'extension-mobility',
      'handset', 'handset-alert', 'handset-down-slash', 'handset-muted',
      'handsets-arrow-left', 'headset', 'headset-alert', 'headset-arrow-down',
      'headset-bluetooth', 'headset-muted', 'headset-private', 'helpdesk',
      'hunt-group', 'incoming-call-legacy', 'move-call-in-adr', 'move-call-in-iph',
      'move-call-in-laptop', 'move-call-in-out-adr', 'move-call-in-out-iph',
      'move-call-in-tablet', 'move-call-out-adr', 'move-call-out-iph',
      'move-call-out-laptop', 'move-call-out-tablet', 'other-number',
      'other-number-warning', 'outgoing-call-legacy', 'paired-handset', 'parked',
      'phone', 'phone-alert', 'phone-muted', 'phone-private', 'phone-reply',
      'phone-reply-all', 'pull-call', 'queue-contact', 'queued-interaction',
      'retrieve-call', 'secure-call-lock', 'secure-call-shield', 'send-digits',
      'single-number-reach', 'speed-dial', 'voicemail', 'new-voicemail',
      'urgent-voicemail', 'visionpro-move-call-in', 'visionpro-move-call-in-out',
      'visionpro-move-call-out', 'whisper-announcement', 'whisper-coach', 'workphone',
    ],
  },
  {
    id: 'content',
    label: 'Content',
    icons: [
      'attachment', 'broken-file', 'cloud', 'cloud-download', 'cloud-frame',
      'cloud-muted', 'cloud-upload', 'content-download', 'document',
      'document-camera', 'document-camera-disconnected', 'document-create',
      'document-move', 'document-share', 'file-analysis', 'file-annotation',
      'file-audio', 'file-bug', 'file-code', 'file-dashboard', 'file-excel',
      'file-graph', 'file-image', 'file-image-none', 'file-js', 'file-keynote',
      'file-locked', 'file-missing', 'file-music', 'file-onenote', 'file-pdf',
      'file-powerpoint', 'file-spreadsheet', 'file-text', 'file-three-d',
      'file-vector', 'file-video', 'file-word', 'file-xml', 'file-zip',
      'files', 'folder', 'folder-edit', 'folder-lock', 'folder-view',
      'note', 'note-ppt', 'notes', 'presentation', 'save-transcript',
      'screenshot', 'screenshot-doc', 'stored-info', 'transcript',
      'whiteboard', 'whiteboard-content',
    ],
  },
  {
    id: 'emoji',
    label: 'Emoji',
    icons: [
      'applause', 'emoji-excited', 'emoji-happy', 'emoji-passive', 'emoji-sad',
      'emoji-unhappy', 'reactions',
    ],
  },
  {
    id: 'feedback',
    label: 'Feedback',
    icons: [
      'ask-for-help', 'dislike', 'help', 'help-circle', 'like', 'poll',
      'q-a', 'quality', 'raise-hand', 'lower-hand', 'survey',
    ],
  },
  {
    id: 'formatting',
    label: 'Formatting',
    icons: [
      'block-quote', 'bold', 'caps-lock', 'code-block', 'colour-palette',
      'family-font', 'fill-colour', 'format', 'formula', 'heading-one',
      'heading-three', 'heading-two', 'horizontal-line', 'indent-decrease',
      'indent-increase', 'italic', 'list-bulleted', 'list-menu', 'list-numbered',
      'markdown', 'number', 'parenthesis', 'pre-header', 'spell-checker',
      'strikethrough', 'subscript', 'superscript', 'text', 'text-align-center',
      'text-align-left', 'text-align-right', 'text-code-block', 'text-highlight',
      'underline',
    ],
  },
  {
    id: 'layout',
    label: 'Layout',
    icons: [
      'align', 'align-bottom', 'align-horizontal-center', 'align-left',
      'align-right', 'align-top', 'align-vertical-center', 'application-panel',
      'area-selector', 'center', 'center-aligned', 'distribute-horizontal',
      'distribute-vertically', 'dock-window', 'fit-to-width',
      'fit-to-window-expand', 'fit-to-window-shrink', 'four-column',
      'layout-side-by-side-vertical', 'maximize', 'minimize', 'one-column',
      'pip', 'pip-enter', 'pip-exit', 'pop-in', 'pop-out', 'pop-up',
      'resize-corner', 'responsive-mobile', 'rotate-content', 'side-panel',
      'split-view', 'three-column', 'two-column', 'view-all', 'view-list',
      'view-stacked', 'view-thumbnail',
    ],
  },
  {
    id: 'navigation',
    label: 'Navigation',
    icons: [
      'arrow-circle-down', 'arrow-circle-left', 'arrow-circle-right',
      'arrow-circle-up', 'arrow-down', 'arrow-left', 'arrow-right',
      'arrow-tail-down', 'arrow-tail-up', 'arrow-up', 'back',
      'back-to-full-screen', 'back-to-top', 'backspace', 'dropdown',
      'enter-room', 'explore', 'home', 'move-to-bottom', 'move-to-screen',
      'move-to-top', 'next', 'overflow-left', 'overflow-right', 'return',
      'secondary-arrow', 'show', 'sign-in', 'sign-in-forced', 'sign-out',
      'tabs', 'waffle-menu',
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    icons: [
      'accessibility', 'accessories', 'accordian', 'admin', 'agent-unique-code',
      'airplay', 'analysis', 'app-push', 'appearance', 'application',
      'applications', 'apps', 'area-chart', 'assets', 'barcode',
      'battery-charging', 'battery-empty', 'battery-high', 'battery-low',
      'battery-medium', 'bluetooth', 'bluetooth-muted', 'boolean', 'box',
      'breakout-session', 'brightness', 'brightness-auto', 'brightness-high',
      'brightness-low', 'browser', 'button-cursor', 'calendar-add',
      'calendar-day', 'calendar-empty', 'calendar-external', 'calendar-filter',
      'calendar-month', 'calendar-month-more', 'calendar-today', 'calendar-week',
      'calendar-week-view', 'calendar-work-week', 'cellular', 'certificate',
      'certificate-invalid', 'certified', 'checkbox-group', 'coffee',
      'color', 'color-accessories', 'color-send', 'computer', 'conditional-block',
      'connect', 'contrast', 'cpu', 'cucm-connection', 'custom-code-editor',
      'custom-task', 'custom-task-ind', 'daily-recurring-schedule', 'dashboard',
      'data-management', 'data-range-selection', 'deployment-evaluation-progress',
      'deployment-progress', 'deployment-recurring', 'deployment-winner-pending',
      'desk-phone', 'desk-phone-warning', 'device-connection', 'device-in-room',
      'device-in-room-end', 'device-muted', 'device-policy-controller', 'devices',
      'diagnostics', 'diamond', 'directional-pad', 'directory', 'disc',
      'disc-connected', 'disconnect', 'display', 'display-input', 'display-warning',
      'divide', 'donut-chart', 'drive-mode', 'dx-eighty', 'dx-seventy',
      'education', 'email', 'email-delivered', 'email-failure', 'email-invite',
      'email-outgoing', 'email-read', 'endpoint', 'endpoint-blocked',
      'endpoint-g-two', 'endpoint-g-two-seventy', 'endpoint-g-two-seventy-dual',
      'endpoint-g-two-stand', 'endpoint-mx-eight-hundred',
      'endpoint-mx-eight-hundred-dual', 'endpoint-stand', 'endpoint-warning',
      'ethernet', 'exchange', 'existing-target-group', 'food', 'forecast',
      'format-default-app', 'format-panel-control-bar', 'format-panel-control-down',
      'format-panel-control-left', 'format-panel-control-right',
      'format-panel-control-up', 'format-panel-control-up-down', 'format-view-mixed',
      'four-way-navigation', 'frequency-capping', 'generic-device-video', 'gift',
      'green-leaf', 'green-room', 'guest-issuer', 'guide', 'hand-pointer',
      'handler', 'handler-horizontal', 'handshake', 'hearing', 'hearing-impaired',
      'hoteling', 'humidity', 'in-common', 'inbox', 'incognito',
      'input', 'input-disconnected', 'instant-schedule', 'integer', 'integrations',
      'interaction', 'keep-in-touch', 'keyboard', 'keyboard-close', 'language',
      'laptop', 'laptop-disconnected', 'laser-pointer', 'live', 'location',
      'long-text-box', 'marker', 'mcp', 'meet', 'meet-end',
      'meetings', 'meetings-focus-month', 'meetings-focus-one-day',
      'meetings-focus-three-day', 'meetings-focus-upcoming', 'meetings-team',
      'meetings-team-new', 'mind-map', 'mirror', 'monitoring',
      'monthly-recurring-schedule-node', 'mouse-cursor', 'multiline-chart',
      'multipled-devices', 'network-switch', 'new-manager', 'new-title',
      'new-whiteboard', 'no-devices', 'old-remote', 'old-touch', 'one-time',
      'paired-camera', 'paired-device', 'pairing', 'parse', 'partial',
      'picker', 'pie-chart', 'plug-ac', 'pmr', 'portrait-landscape',
      'potential-fraud', 'power', 'power-ac', 'premium', 'privacy-circle',
      'private', 'private-circle', 'private-meeting', 'product-demo',
      'proximity', 'proximity-muted', 'proximity-video', 'qr-code',
      'qr-code-scan', 'quiet', 'radio-button-group', 'ram',
      'recurring', 'recurring-off', 'room-calendar', 'room-lights', 'rss',
      'rule-based', 'ruler', 'running-application', 'schedule-send', 'schedule-winner',
      'scheduler-available', 'scheduler-not-working-hours', 'scheduler-unavailable',
      'scheduler-unknown', 'secure-circle', 'secure-lock', 'server', 'server-error',
      'services', 'set-variable', 'settings', 'setup-assistant', 'sftp',
      'shape-circle', 'shape-diagonal-line', 'shape-diamond', 'shape-oval',
      'shape-square', 'shape-triangle', 'shapes', 'share-c-native-adr',
      'share-c-native-iph', 'share-content-on-device', 'shield',
      'short-text-box', 'sign-lang-int', 'signal-four', 'signal-one',
      'signal-three', 'signal-two', 'signal-zero', 'simple-promotion',
      'sip-registration-in-progress', 'stacked-area-chart',
      'stacked-area-chart-full', 'stacked-bar-chart', 'stacked-bar-chart-full',
      'stethoscope', 'stickies', 'sx-eighty-codec', 'sx-ten', 'sx-twenty',
      'table', 'table-extender', 'tablet', 'tap', 'telepresence',
      'telepresence-alert', 'telepresence-alert-muted',
      'telepresence-ix-five-thousand', 'telepresence-muted', 'telepresence-private',
      'temperature', 'test-tube', 'three-d-object', 'time-exclusion', 'timezone',
      'too-fast', 'too-slow', 'tools', 'touch-ten', 'translate',
      'translate-undo', 'trending', 'trending-down', 'trim', 'ucm-cloud',
      'unsecure-unlocked', 'usb', 'usb-headset', 'usb-headset-muted',
      'visionpro', 'vpn', 'vsc', 'waiting-room', 'wallpaper',
      'webex-board', 'webhook', 'webinar', 'weekly-recurring-schedule',
      'widget', 'wifi', 'wifi-error', 'wifi-signal-good', 'wifi-signal-poor',
      'wifi-signal-unstable', 'window-corner-scrub', 'window-right-corner-scrub',
      'window-vertical-scrub', 'workflow-deployments',
    ],
  },
  {
    id: 'people',
    label: 'People',
    icons: [
      'admin', 'annotate', 'allow-to-annotate', 'contact-card', 'contacts',
      'create-a-group', 'end-remote-desktop-control', 'external-user', 'guest-issuer',
      'invited-user', 'moderator', 'participant', 'participant-add',
      'participant-blocked', 'participant-list', 'participant-remove',
      'participant-speaker', 'participant-unknown', 'people', 'people-add',
      'people-circle', 'people-insights', 'people-manage', 'primary-participant',
      'remote-desktop-control', 'user', 'user-deactivate',
    ],
  },
  {
    id: 'presence',
    label: 'Presence',
    icons: [
      'active-interaction', 'active-speaker', 'active-speaker-alert',
      'active-speaker-lock', 'advance-schedule', 'away-calling-presence',
      'blocked', 'busy-presence', 'camera-presence', 'dnd-presence', 'idle',
      'leave-breakout-session', 'leave-device', 'meetings-presence',
      'pause-interaction', 'pto-presence', 'quiet-hours-presence',
      'recents-presence', 'resume-interaction',
    ],
  },
];

/** Flat array of all icon names (895 icons with regular + bold variants). */
export const ALL_ICON_NAMES: readonly IconName[] = ICON_CATEGORIES.flatMap(
  (cat) => cat.icons,
).filter((name, idx, arr) => arr.indexOf(name) === idx) as IconName[];

/** Look up which category an icon belongs to. */
export function getCategoryForIcon(name: IconName): IconCategory | undefined {
  return ICON_CATEGORIES.find((cat) => (cat.icons as string[]).includes(name));
}

/** Get all icons in a given category. */
export function getIconsByCategory(categoryId: string): IconName[] {
  return (ICON_CATEGORIES.find((cat) => cat.id === categoryId)?.icons ?? []) as IconName[];
}
